Assets/Prefabs/UI/GenericOption.prefab
Assets/Script/UI/DifficultySelect.cs
Assets/Script/UI/GenericOption.cs

Editing generic options prefab, script, and difficulty settings script to add mouse support to the difficulty menu

Mouse support in the difficulty menu

---

Assets/Scenes/PlayScene.unity
Assets/Script/GameManager.cs
Assets/Script/PlayMode/Play.cs
Assets/Script/Serialization/Audio.meta
Assets/Script/Serialization/Audio/AudioHandler.cs
Assets/Script/Serialization/Audio/AudioHandler.cs.meta
Assets/Script/Serialization/Audio/OpusAudioHandler.cs
Assets/Script/Serialization/Audio/OpusAudioHandler.cs.meta
Assets/Script/Serialization/Audio/WWWAudioHandler.cs
Assets/Script/Serialization/Audio/WWWAudioHandler.cs.meta
Assets/Script/UI/GameUI.cs
Assets/Script/UI/GameUI.cs.meta
Assets/packages.config

Audio handlers

---

Assets/Scenes/MenuScene.unity
Assets/Scenes/PlayScene.unity
Assets/Script/UI/PauseMenu.cs
Assets/Script/UI/PauseMenu.cs.meta

Pulled the Pause Menu out of the main canvas and put it on its own canvas alongside copying the Difficulty Select script and calling it the Pause Menu script, dumbing it down just for Resume, Quit. Not functional currently.

Pause Menu

---

Assets/Script/Serialization/SongsDta.cs
Assets/Script/Serialization/SongsDta.cs.meta
Assets/Script/SongLibrary.cs

It is *definitely* not finished, and I haven't had the time to test it with multi-song files yet, but this should work for "showing the song(s) defined in the library".

INCOMPLETE Add songs.dta reading support

---

Assets/Script/DiscordController.cs
Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/MicPlayer.cs
Assets/Script/PlayMode/Play.cs

Added two events to the play script (OnSongStart and OnSongExit), then redid a bunch of the discord manager script.

Adding song/artist/length support to discord rich presence

---

Assets/Script/DiscordController.cs
Assets/Script/PlayMode/Play.cs
Assets/Script/UI/DifficultySelect.cs

Mostly through 3 new events.
Added some AI generated Icons to the app (Avoiding any copyrighted material) as well

Added instrument icons and timer pause to discord rich presence

---

Assets/Script/DiscordController.cs

Changed from song length played to calc'ing the total pause time

Fixing the pause time "bug"

---

Assets/Script/PlayMode/FiveFretTrack.cs

Currently, strumming ALWAYS tries to hit the earliest possible note, which is good for FC runs, not so great if you've missed and there are multiple notes in the timing window (as the note you intend on strumming might not be the note the game thinks you're strumming).
This makes it so strumming finds the first valid note within the timing window (auto-missing any notes prior to that one), making combo recovery much easier.
I've also done my best to ensure this doesn't cause any wrong misses, including accounting for allowed overstrums.
Tested on TTFAF (RB3 chart) and Soulless 5.

Make five fret combo recovery more natural

---

Assets/Script/PlayMode/FiveFretTrack.cs

Infinite front-end window can be readded by setting INFINITE_FRONTEND to true; it's a "feature" in GH3/CH, but not in every other game.
Tested on Raining Blood (GH:SH chart, taps to ho/pos) and Misirlou (GH2 chart, all ho/pos)

(Five-fret) Fix infinite front-end (toggle) & multi ho/po hits

---

.gitignore

- Updated the .gitignore to ignore files generated by JetBrains Rider IDE

Ignore Rider .idea folder

---

Assets/Script/PlayMode/FiveFretTrack.cs
Assets/Script/PlayMode/Play.cs

GH3+/CH feature; some custom songs (such as Soulless 4) rely on this mechanic to be playable.

Allow anchoring chord HO/POs (togglable)

---

Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Settings/Localization/Settings_en-US.asset

Awesomeness Detection

---

Assets/Script/ThirdParty/DiscordController.cs

for defaultSmallImage and defaultSmallText

Minor cleanup, eliminating unused variable messages

---

Assets/Script/ThirdParty/TwitchController.cs

+ Added more song information in the TXT, JSON still would be really good, but its already possible to do a lot with the .txt and some crops in the Text Source --- Album
--- Genre
--- Year
--- Source
--- Charter
+ Changed the way the code works to just empty the files when its not in a song, this avoids some errors in OBS if you open the software and its not in a song for example

Updated CurrentSong.txt

---

Assets/Art/Materials/PlayMode/Note_Tap.mat
Assets/Art/Materials/PlayMode/Note_Tap.mat.meta
Assets/Art/Meshes/Notes.blend1.meta
Assets/Art/Meshes/Notes_HOPO.prefab
Assets/Art/Meshes/Notes_Tap.prefab
Assets/Art/Meshes/Notes_Tap.prefab.meta
Assets/Art/Textures/PlayMode/Note_Tap.png
Assets/Art/Textures/PlayMode/Note_Tap.png.meta
Assets/Prefabs/AbstractTrack.prefab
Assets/Prefabs/Note.prefab
Assets/Prefabs/PlayMode/Note_Tap.mat
Assets/Prefabs/PlayMode/Note_Tap.mat.meta
Assets/Script/Pools/NoteComponent.cs
Assets/Script/ThirdParty/TwitchController.cs

+ Updated HOPO Model, easier to see now in intense songs
+ Added Tap Note Model

Notes Update!

---

Assets/Script/PlayMode/FiveFretTrack.cs
Assets/Script/Serialization/Parser/MidiParser.FiveFret.cs

This reads open HO/POs, both auto and forced
Pending visuals, currently looks the same as regular opens (I'll most likely need help with this)

Open HO/POs

---

Assets/Art/Materials/PlayMode/Trim_Dark.mat
Assets/Art/Materials/PlayMode/Trim_Light.mat
Assets/Art/Textures/PlayMode/Full_Outline.mat
Assets/Art/Textures/PlayMode/Full_Outline.mat.meta
Assets/Art/Textures/PlayMode/Note_Full.png
Assets/Art/Textures/PlayMode/Note_Full_HOPO.png
Assets/Art/Textures/PlayMode/Note_Full_HOPO.png.meta
Assets/Art/Textures/PlayMode/Note_Full_HOPO.shadergraph
Assets/Art/Textures/PlayMode/Note_Full_HOPO.shadergraph.meta
Assets/Note_Full_Metal_HOPO.mat
Assets/Note_Full_Metal_HOPO.mat.meta
Assets/Notes_Full_HOPO.prefab
Assets/Notes_Full_HOPO.prefab.meta
Assets/Prefabs/AbstractTrack.prefab
Assets/Prefabs/DrumsTrack.prefab
Assets/Prefabs/FiveFretTrack.prefab
Assets/Prefabs/GHDrumsTrack.prefab
Assets/Prefabs/Note.prefab
Assets/Prefabs/PlayMode/Note_Full.mat

+ Added new texture for Open/Kicks
+ Added new texture/shader for Open HOPO, still need some tweaks from someone that understand shaders better
+ Tweaked Highway design a bit (just the sides, look better with the kicks and opens now)

Open Notes and Highway

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassMoggStem.cs
Assets/Script/Audio/Bass/BassMoggStem.cs.meta
Assets/Script/Audio/Bass/BassStemChannel.cs
Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/Audio/Interfaces/IStemMixer.cs
Assets/Script/Data/SongInfo.Sources.cs
Assets/Script/PlayMode/Play.cs
Assets/Script/Serialization/Xbox/XboxMoggData.cs
Assets/Script/Serialization/Xbox/XboxSong.cs
Assets/Script/SongLibrary.cs

Adds support for mogg files from RB cons/rawfiles

Add MOGG audio loading

---

Assets/Scenes/MenuScene.unity
Assets/Script/Input/InputStrategy.cs
Assets/Script/UI/AddPlayer.cs

Fixes:
- Fixed keyboard keys not being mappable
- Added a time period for mapping resolution (current is 100 ms) to further assist in resolving conflicts
- Fixed alignment settings and placement of the helpbar
- Made `InputStrategy.IsControlPressed` also work in terms of `InputControl<float>`
- Fixed noisy and synthetic controls not being mappable
New features:
- Added a Back button to the helpbar
- Added toggles for enabling/disabling mapping of button, axis, noisy, and synthetic controls

Some mapping menu fixes and improvements

---

Assets/Script/UI/PauseMenu.cs

like the title says it adds a restart option to the pause menu.
also this is my first time coding in c# so im sorry if the code is bad.

Adds a "Restart" option to the pause menu

---

Assets/Art/Materials/PlayMode/Sustain.mat
Assets/Art/Shaders/Subgraphs.meta
Assets/Art/Shaders/Subgraphs/WaveyUV.shadersubgraph
Assets/Art/Shaders/Subgraphs/WaveyUV.shadersubgraph.meta
Assets/Art/Shaders/SustainLine.shadergraph
Assets/Art/Shaders/SustainLine.shadergraph.meta
Assets/Art/Textures/PlayMode/Sustain_Thin.png
Assets/Art/Textures/PlayMode/Sustain_Thin.png.meta
Assets/Script/Pools/NoteComponent.cs

https://user-images.githubusercontent.com/29520859/235312868-c6b9e863-f66a-4a38-87d0-c14d45b2b9dd.mov
Has adjustable parameters, and can be easily modified for whammy in the future.

Created the note sustain shader and implemented it

---

Assets/Script/Audio/Bass/BassStemChannel.cs

Was told the reverb cutting in/out with star power was too sharp so I changed it to slide over 200ms in and 250ms out

Slide reverb volume up and down

---

Assets/Script/Audio/Bass/BassStemChannel.cs

ChanGed **H**ow s**E**mitone sHifting is ca**L**culaTed for Chi**P**munk SpeeDups...

Unleash the Chipmunks and the Demons

---

Packages/manifest.json
Packages/packages-lock.json

Lots of issues fixed since the last time I updated them here lol
Closes #232 and should solve a number of issues reported in the Discord.

Update PlasticBand-Unity to v0.2.2 and HIDrogen to v0.2.0

---

Assets/Art/UI/PlayMode/ScoreBox/Star_gold_progress.png
Assets/Art/UI/PlayMode/ScoreBox/Star_gold_progress.png.meta
Assets/Prefabs/UI/ScoreDisplay/ScoreDisplay.prefab

Has brighter border so it should be more visible

Replace gold star progress sprite with a brighter one

---

README.md

"Be sure it is added to system path." twice and "greater" for python

Added some clarification

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassHelpers.cs
Assets/Script/Audio/Bass/BassMoggStem.cs
Assets/Script/Audio/Bass/BassStemChannel.cs
Assets/Script/LoadingManager.cs
Assets/Script/PlayMode/Play.cs
Assets/Script/Serialization/Xbox/XboxSong.cs
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/Song/Preparsers/ChartPreparser.cs
Assets/Script/Song/Preparsers/MidPreparser.cs
Assets/Script/Song/SongCache.cs
Assets/Script/Song/SongContainer.cs
Assets/Script/Song/Types/SongEntry.cs

- Fixed song length for excons being converted incorrectly
- Adjusted slide in/out timings for star power reverb to minimise how jarring it can be
- Hardcoded a multiplier for song volume to help with volume balancing
- Changed some default volume settings
- Added a 2 second delay before the song plays (to help with songs that have notes on tick 0 being hard to hit)

Bunch of small changes/fixes

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassHelpers.cs
Assets/Script/Audio/Bass/BassMoggStem.cs
Assets/Script/Audio/Bass/BassStemChannel.cs
Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/Audio/Interfaces/IStemChannel.cs
Assets/Script/Audio/Interfaces/IStemMixer.cs

Adds some functionality to load preview audio, as well as some fade in and out functions

Add preview audio loading code

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/PlayMode/Play.cs

Simplify loading of moggs for CON and exCON

---

Assets/Art/Fonts/Barlow/Barlow-Bold.asset
Assets/Art/UI/Fps_Circle.png
Assets/Art/UI/Fps_Circle.png.meta
Assets/Scenes/PersistantScene.unity
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/Settings/SettingsManager.cs
Assets/Script/UI/FpsCounter.cs
Assets/Script/UI/FpsCounter.cs.meta
Assets/Settings/Localization/Settings Shared Data.asset
Assets/Settings/Localization/Settings_en-US.asset

[Added]
- FPS_Circle Asset
- An option at Setting to enable the counter
- FpsCounter Script
- Entry in Localization
[Changed]
- Elements at persistant Scene

FPS Counter

---

Assets/Script/Settings/SettingsDirectory.cs

[Issue 293] new folder song count doesnt update on refresh

---

.gitignore
Assets/Art/Materials/PlayMode/Shader Graphs_HighwayFadeout.mat
Assets/Art/Materials/PlayMode/Shader Graphs_HighwayFadeout.mat.meta
Assets/Art/Shaders/HighwayFadeFix.shader
Assets/Art/Shaders/HighwayFadeFix.shader.meta
Assets/Art/Shaders/HighwayFadeout.shadergraph
Assets/Art/Shaders/HighwayFadeout.shadergraph.meta
Assets/Scenes/PlayScene.unity
Assets/Script/UI/GameUI.cs

Title, since it's procedurally created it allows for customization of length and fade down the road by setting the Smooth Step material property.

Highway Fadeout Shader

---

Assets/Script/Song/Scanning/SongScanThread.cs
Assets/Script/Song/Scanning/SongScanner.cs
README.md

2 commits here, Removed a duplicate part from the readme (the merge part) and Changed the error struct to add a file name. Added to when a con error is scanned, "" gets added for .ini songs

Updated Readme to remove duplicate

---

Assets/Script/UI/MusicLibrary/SongSelection.cs

Small PR that fixes index out of bounds error when scrolling up & down the song library

Fixed Scrolling Bugs

---

Assets/Script/UI/PlayerSection.cs

Support for two decimals in the track speed field

Track speed to two decimals

---

Assets/Script/ThirdParty/TwitchController.cs

JsonUtility should not be used.

Changed to JsonConvert from JsonUtility

---

Assets/Script/Serialization/Parser/MidiParser.cs

Midi parser reads in latin1 for RB song types, and UTF-8 for everything else

change encoding depending on song type

---

Assets/Art/Textures/PlayMode/Track_Normal.png

https://discord.com/channels/1086048856678084609/1107318936741085296/1107318936741085296

Update Track texture (credit Mia)

---

Assets/Script/Serialization/Xbox/XboxDTAParser.cs
Assets/Script/Song/SongCache.cs
Assets/Script/Song/Types/ExConSongEntry.cs
Assets/Script/Song/Types/SongEntry.cs

-master checks if a song is by the official artist or an "as made famous by" cover
-vocal parts: how many vocal parts the song has (0 for CH, 1-3 for RB)

add master and vocal part SongEntry members

---

Assets/Art/Materials/PlayMode/StarpowerBar_Top.mat
Assets/Art/Shaders/StarpowerBar.shadergraph

Proposal - https://discord.com/channels/1086048856678084609/1107320071270977576/1107320071270977576

update overdrive shader (credit Mia)

---

Assets/Prefabs/UI/HelpBarV2.prefab
Assets/Prefabs/UI/HelpBarV2_Button.prefab
Assets/Prefabs/UI/MusicLibrary/MusicLibrary.prefab
Assets/Prefabs/UI/PlayResultScreen/PlayResultScreen.prefab
Assets/Scenes/MenuScene.unity
Assets/Script/UI/HelpBarButton.cs
Assets/Script/UI/HelpBarButton.cs.meta

Still need to remove all instances of the original HelpBar prefab, then delete the prefabs

Replace old HelpBar with HelpBarV2 on most (if not all) reachable screens

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassMicDevice.cs
Assets/Script/Audio/Bass/BassMicDevice.cs.meta
Assets/Script/Audio/Interfaces/IMicDevice.cs
Assets/Script/Audio/Interfaces/IMicDevice.cs.meta

Added the foundations for recording with BASS, just need to write functions to calculate pitch and amplitude values and hook it into the rest of the audio system

Start bass recording implementation

---

Assets/Prefabs/UI/DifficultyRing.prefab
Assets/Script/UI/MusicLibrary/DifficultyRing.cs
Assets/Script/UI/MusicLibrary/SongSelection.cs

1. Clicking on instrument when selected song has it filters search results by that instrument
2. Or you can type in `instrument:guitar`, `instrument:bass`, etc.. in the search filters to show songs with that instrument

Added Search Filter based on Instrument

---

Assets/Script/UI/MusicLibrary/SongSelection.cs

* Removed diacritics from search bar for song, album and artist names searches
- Tested characters: ÁáÀàÂâǍǎĂăÃãẢảẠạÄäÅåĀāĄąẤấẦầẪẫẨẩẬậẮắẰằẴẵẲẳẶặǺǻĆćĈĉČčĊċÇçÉéÈèÊêĚěĔĕẼẽẺẻĖėËëĒēĘęẾếỀềỄễỂểẸẹỆệĞğĜĝĠġĢģÍíÌìĬĭÎîǏǐÏïĨĩĮįĪīỈỉỊịĴĵĶķĹĺĽľĻŃńŇňÑñŅņÓóÒòŎŏÔôỐốỒồỖỗỔổǑǒÖöŐőÕõỜờỠỡỞởỢợỌọỘộỎỏƠơỚớṔṕṖṗŔŕŘřŖŗŚśŜŝŠšŞşŤťŢÚúÙùŬŭÛûǓǔŮůÜüǗǘǛǜǙǚǕǖŰűŨũŲųŪūỦủƯưỨứỪừỮữỬửỰựỤụẂẃẀẁŴŵẄẅÝýỲỳŶŷŸÿỸỹỶỷỴỵŹźŽžŻż
* Autofocus search bar at song selection start

Removed diacritics from search bar for song, album and artist names searches and autofocus search bar at song selection start

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassMicDevice.cs
Assets/Script/Audio/Interfaces/IMicDevice.cs
ProjectSettings/AudioManager.asset

Thanks EA for finding that setting (Unity moment L). EA please implement pitch and amplitude detection in this new system now thank you 😃
Had to remake my branch because I tried to merge changes from dev and ended up with 5 bazillion merge conflicts very cool

Fixed latency issues with new mic implementation

---

Assets/Scenes/PlayScene.unity
Assets/Script/Audio/Bass/BassMicDevice.cs

Will help with not being able to speak due to small delay, will need adjusting in the future.

Add reverb to new vocal monitoring

---

Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/FiveFretTrack.cs
Assets/Script/PlayMode/MicPlayer.cs

* Fixed held frets getting stuck upon pausing (#208)
* Fixed divide-by-zero error with empty vocal charts

Minor bugfixes

---

Assets/Script/PlayMode/Play.cs
Assets/Script/Song/ScanHelpers.cs

Songs with a delay tag in the song.ini now play correctly. Also accounts for 2 different delay formats, integer format and decimal format (150 vs 0.15/.15)

Implement song delay

---

Assets/Script/Serialization/Parser/MidiParser.cs

These errors were already avoided for preparsing, but the fix was never applied to the parser itself.

Fix some errors that could occur when loading .mid charts

---

Packages/manifest.json
Packages/packages-lock.json

Finally figured out the crash with these and found a workaround, let's hope there aren't any other issues like this lol

Fix and re-enable PS4 and Santroller instrument support (Update PlasticBand-Unity to v0.3.2)

---

Assets/Script/Input/MicInputStrategy.cs
Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/DrumsTrack.cs
Assets/Script/PlayMode/FiveFretTrack.cs
Assets/Script/PlayMode/MicPlayer.cs
Assets/Script/PlayMode/RealGuitarTrack.cs
Assets/Script/Pools/NoteComponent.cs
Assets/Script/Serialization/Parser/MidiParser.cs
Assets/Script/UI/TrackView.cs

I need to try harder to avoid making more broad changes like this lol, it's just difficult when there are so many things that could be done better or need to be fixed
Highlighted changes/fixes:
- Events such as starpower phrases, solos, and drum fills are now allocated into dedicated lists ahead of time, rather than having a single field for the current one and checking the name on-the-fly. The current visual and logical events are also tracked using separate indexes, rather than attempting to use the same field for both.
- This fixes back-to-back solos not working correctly, as well as issues where events could sometimes get skipped (or effectively merged together).
- Starpower note coloring has been made much more consistent: rather than checking the current visual phrase, the note is …

A whole slew of track logic fixes

---

Assets/Script/Song/SongCache.cs
Assets/Script/Song/Types/ConSongEntry.cs
Assets/Script/Song/Types/ExConSongEntry.cs

Ensure HasAlbumArt is set on cache read 

---

Assets/Script/Song/SongSorting.cs
Assets/Script/UI/MusicLibrary/SongSelection.cs

* Removed articles for the artist search with blue button
+ Added articles in Spanish (El, La, Los)
+ TODO: Add articles in other languages
* Fix advance to next section for songs without album, charter or year
+ Set a space as a safe value

More enhancements to advance to new section and artist search

---

Assets/Art/Textures/PlayMode/VocalBar_Front.png
Assets/Art/Textures/PlayMode/VocalBar_Front.png.meta
Assets/Art/Textures/PlayMode/VocalBar_Mask.png
Assets/Art/Textures/PlayMode/VocalBar_Rim.png
Assets/Art/UI/PlayMode/VocalCombo_Background.png
Assets/Art/UI/PlayMode/VocalCombo_Fill.png
Assets/Art/UI/PlayMode/VocalCombo_Fill_Max.png
Assets/Art/UI/PlayMode/VocalCombo_Rim.png
Assets/Art/UI/PlayMode/VocalCombo_Rim_Max.png
Assets/Art/UI/PlayMode/VocalCombo_Rim_Max_StarPower.png
Assets/Art/UI/PlayMode/VocalStarpower_Background.png
Assets/Art/UI/PlayMode/VocalStarpower_Background.png.meta
Assets/Art/UI/PlayMode/VocalStarpower_Fill.png
Assets/Art/UI/PlayMode/VocalStarpower_Overlay.png
Assets/Art/UI/PlayMode/VocalStarpower_Rim.png
Assets/Prefabs/VocalNeedle.prefab
Assets/Scenes/PlayScene.unity

- Harmonies Multipliers
- Combo Meter
- Overdrive

Updated some Vocal graphics

---

Assets/Script/Audio/Bass/BassMicDevice.cs
Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/FiveFretTrack.cs
Assets/Script/PlayMode/MicPlayer.cs
Assets/Script/PlayMode/RealGuitarTrack.cs
Assets/Script/Serialization/Parser/MidiParser.FiveFret.cs
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/UI/MusicLibrary/SongSelection.cs
Assets/Script/Util/ParticleGroup.cs

Post-release bug reports, yay! Except for the 4th commit, I just happened to realize that was a thing that could happen lol

Even more smaller fixes

---

Assets/Script/UI/PostSong.cs

Fixed DQ above 100% sped up songs

---

Assets/Scenes/PersistantScene.unity
Assets/Script/ThirdParty/DiscordController.cs

[Added]
- New Stable Logo
- Dev Logo
- Nightly Logo
[Fixed]
- Song Left Time

Discord RP Update

---

Assets/Script/PlayMode/FiveFretTrack.cs

The check for whammyAmount > 0 is now OR'd with input.BotMode.

Five lane bots now auto-whammy

---

Assets/Credits.json

thanks discord, **_REAL_** productive update ya got

remove muskit's discord discriminator

---

Assets/Script/Serialization/Parser/MidiParser.Venue.cs

[FogOn] to  "venue_fog_on" and [FogOff] to "venue_fog_off"

Update MidiParser.Venue.cs to parse Fog

---

Assets/Script/Serialization/Parser/MidiParser.Vocals.cs

Improve differentiation between text events and lyric events in vocals parsing

---

Assets/Script/Data/GenericLyricInfo.cs
Assets/Script/Data/YargChart.cs

Right before I tested this I thought I would have to also handle the markup characters here, but to my surprise it just worked lol

Implement .chart lyrics parsing

---

Assets/Credits.json

Changes
- Remove discriminator for PikminGuts92
- Update YouTube URL for PikminGuts92

Remove discord discrimator and update YT url for PikminGuts92

---

Assets/Prefabs/UI/MusicLibrary/MusicLibrary.prefab
Assets/Script/LoadingManager.cs
Assets/Script/Settings/SettingsMenu.cs
Assets/Script/Song/SongSearching.cs
Assets/Script/Song/SongSorting.cs
Assets/Script/UI/MusicLibrary/DifficultyRing.cs
Assets/Script/UI/MusicLibrary/Sidebar.cs
Assets/Script/UI/MusicLibrary/SongSelection.cs
Assets/Script/UI/MusicLibrary/SongView.cs
Assets/Script/UI/MusicLibrary/ViewTypes/SongViewType.cs
Assets/Script/UI/MusicLibrary/ViewTypes/SortHeaderViewType.cs
Assets/Script/UI/MusicLibrary/ViewTypes/SortHeaderViewType.cs.meta
ProjectSettings/ProjectSettings.asset

The current system is extremely slow if you have a ton of songs. This fixes that.

Greatly optimized and refactored sorting and searching code

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassMoggStemChannel.cs
Assets/Script/Audio/Bass/BassStemChannel.cs
Assets/Script/Audio/Bass/PitchShiftWindowsParameters.cs
Assets/Script/Audio/Bass/PitchShiftWindowsParameters.cs.meta
Assets/Script/Audio/Interfaces/IStemChannel.cs

Start of whammy fx. Need to implement controlling the pitch shift with controller. Just does pitching using a slider in the inspector

Add Whammy pitch shift to BASS

---

Assets/Scenes/PersistantScene.unity
Assets/Script/Song/SongSources.cs
Assets/Script/ThirdParty/DiscordController.cs

Show source icon in Discord RP

---

Assets/Script/PlayMode/CameraPositioner.cs

full disclosure chat gpt wrote this and i just worked through it for a while until it worked

unfurl the track on enter

---

Assets/Script/Menu/PlayResultScreen/PlayResultScreen.cs

This action triggers when the results screen is enabled or exited. Added for the upcoming need of the stage kit to know when to trigger different cues

Add action to PlayResultScreen.cs

---

Assets/Script/Song/SongSearching.cs

Fixed vocal search filter returning everything

---

Assets/Script/ThirdParty/UpdateChecker.cs

fixes 404 not found error in rewrite branch

Fix 404 not found error when trying to update (rewrite branch)

---

Assets/Credits.json

Getting old username back on twitch

NevesPT - Update

---

Packages/manifest.json
Packages/packages-lock.json

Santroller updates, XInput `GuitarBass` support, and Wii RB3 keyboard recognition fixes.

Update PlasticBand-Unity to v0.3.3

---

Assets/Plugins/Editor/YARGCoreBuilder.cs
Assets/Scenes/Gameplay.unity
Assets/packages.config
Packages/manifest.json
Packages/packages-lock.json

the bleeding edge returns
(might want to make a new bake lighting for the gameplay scene, i just used the old from PlayScene folder)

fix: support for batch mode building

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassStemMixer.cs

Two small fixes for some exceptions I ran into while testing

Fix two exceptions when loading songs

---

ProjectSettings/ProjectSettings.asset

fix: user files going into unity default template folder

---

Assets/Prefabs/Menu/Common/FillBar.prefab
Assets/Prefabs/Menu/Common/FillBar.prefab.meta
Assets/Prefabs/Menu/Common/ValueSlider.prefab
Assets/Prefabs/Menu/Profiles/EditProfile/BindViews/AxisBindView.prefab
Assets/Prefabs/Menu/Profiles/EditProfile/BindViews/AxisDisplay.prefab
Assets/Prefabs/Menu/Profiles/EditProfile/BindViews/AxisDisplay.prefab.meta
Assets/Prefabs/Menu/Profiles/EditProfile/BindViews/ButtonBindView.prefab
Assets/Prefabs/Menu/Profiles/EditProfile/BindViews/IntegerBindView.prefab
Assets/Script/Input/Bindings/AxisBinding.cs
Assets/Script/Input/Bindings/ButtonBinding.cs
Assets/Script/Input/Bindings/ControlBinding.cs
Assets/Script/Menu/Profiles/EditProfile/AxisBindView.cs
Assets/Script/Menu/Profiles/EditProfile/AxisDisplay.cs
Assets/Script/Menu/Profiles/EditProfile/AxisDisplay.cs.meta
Assets/Script/Menu/Profiles/EditProfile/ButtonBindView.cs
Assets/Script/Menu/Profiles/EditProfile/IntegerBindView.cs

Each type of binding has its own way of displaying the current value:
- Buttons fill up starting from the left of the bar
- Axes start from the center and fill to the left or right
- Axes like the whammy bar are expected to be normalized from 0 to 1, so they will display from the center to the right
- Integers display the value inside of a text box
The calibration options are as follows:
- Buttons: press point
- Axes: min/max deadzone, min/max value
- Integers: none
Each binding can be calibrated individually, and each of the calibration settings is displayed on the current value display.
https://github.com/YARC-Official/YARG/assets/29052821/bf143ab0-50b0-4c9f-ad0a-7a6687950dd0

Implement various control calibration settings, alongside current value display for bindings

---

Assets/Script/Gameplay/HUD/LyricBar.cs

Would happen at the last lyrics of a song.

Prevent index error in lyric bar

---

Assets/Script/Gameplay/HUD/LyricBar.cs

+ Added clearing of the bar after the end of a phrase (in certain conditions)
+ Optimized how the lyric display gets constructed by ensuring it only updates on lyric changes instead of every frame.

Lyric Bar Updates

---

Assets/Script/Persistent/LoadingManager.cs

Update LoadingManager to account for CacheHandler's conversion to static

---

Assets/Script/Gameplay/BeatEventManager.cs

To unsub it has to ADD it first to the list of things it will REMOVE later.
I can't remove things that are removed from the removed list while removed. Got that?

Fixed an eye-rollingly stupid mistake I made

---

Assets/Script/Gameplay/HUD/LyricBar.cs

For anyone reading gets a better idea of what is going on

Change unicode to the character itself

---

Assets/Script/Gameplay/GameManager.cs

Abort Song Load on Failed Validation

---

Assets/Prefabs/Menu/MusicLibrary/SongView.prefab
Assets/Script/Menu/MusicLibrary/SongView.cs

Adds the ability to select songs via mouse within the MusicLibraryMenu by clicking on song titles.

Added a button to SongView/Primary Text to click

---

Assets/Prefabs/Menu/DifficultySelect/DifficultySelectMenu.prefab
Assets/Prefabs/Menu/MusicLibrary/MusicLibraryMenu.prefab
Assets/Script/Helpers/LocaleHelper.cs
Assets/Script/Menu/Common/Header/HeaderTab.cs
Assets/Script/Menu/Common/Header/HeaderTabs.cs
Assets/Script/Menu/Navigation/NavigatableBehaviour.cs
Assets/Script/Menu/Navigation/NavigationGroup.cs
Assets/Script/Menu/Navigation/NavigationTextColorizer.cs
Assets/Script/Menu/Navigation/ScrollViewNavigationUpdater.cs
Assets/Script/Menu/ProfileList/ProfileView.cs
Assets/Script/Menu/Settings/SettingsMenu.cs

The *one* time I don't check my changes before pushing them, it immediately comes back to bite me lol
Re-do of #624 that should actually work this time, there were a number of issues I didn't come across initially which should now be fixed.

Take two: Clean up navigation group selection handling and fix various issues

---

Assets/Prefabs/Gameplay/Visual/VocalElements/BaseVocalNote.prefab
Assets/Script/Gameplay/Player/Vocals/VocalLyricContainer.cs
Assets/Script/Gameplay/Player/Vocals/VocalTrack.Spawning.cs
Assets/Script/Gameplay/Player/Vocals/VocalTrack.cs
Assets/Script/Gameplay/Visuals/VocalElements/VocalLyricElement.cs
Assets/Script/Gameplay/Visuals/VocalElements/VocalNoteElement.cs

Depends on https://github.com/YARC-Official/YARG.Core/pull/135 and needs a YARG.Core submodule update before merging.

Move more lyric flag handling to YARG.Core, and implement handling of vocals range shifts

---

Assets/Script/Gameplay/Player/BasePlayer.cs
Assets/Script/Gameplay/Player/FiveFretPlayer.cs
Assets/Script/Gameplay/Visuals/TrackElements/NoteElement.cs
Assets/Script/Menu/ScoreScreen/ScoreCards/ScoreCard.cs

Main YARG changes for https://github.com/YARC-Official/YARG.Core/pull/136

Updates needed for sustain scoring addition

---

Assets/Script/Gameplay/GameManager.cs
Assets/Script/Gameplay/Player/BasePlayer.cs

Fixes https://yarg.youtrack.cloud/issue/YARG-114

Fix frets not displaying correctly when pressed/released when the game is paused

---

Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
Assets/Script/Song/SongSources.cs

Display actual name of source in Music Library when sorted by source

---

Assets/Script/Gameplay/HUD/Pause/PauseMenuManager.cs
Assets/Script/Gameplay/PracticeManager.cs

Fix frets not being released correctly when restarting a practice section

---

Assets/Prefabs/Menu/MusicLibrary/MusicLibraryMenu.prefab
Assets/Script/Menu/MusicLibrary/Sidebar.cs

Music library sidebar fixes

---

Assets/Script/Menu/DifficultySelect/DifficultySelectMenu.cs

This just adds a check to make sure that the vocals part actually exists, as well as being the correct style.
Fixes YARG-149

Fix vocals players after the first not being forced to sit out if there are no vocals parts

---

Assets/Script/Menu/MusicLibrary/PopupMenu.cs

From a Discord suggestion.
Makes it so that if you want to jump around randomly, it is quicker to select Random Song.

Move "Random Song" to top of Popup Menu

---

Assets/Script/Helpers/Extensions/SongMetadataExtensions.cs
Assets/Script/Menu/Main/MainMenu.cs
Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
Assets/Script/Menu/Persistent/MusicPlayer.cs

https://yarg.youtrack.cloud/issue/YARG-176/Add-button-to-go-to-currently-playing-song-in-music-player

YARG-176 Add button to go to currently-playing song in music player

---

Assets/Script/Settings/SettingsManager.Settings.cs

Learning is neat. Need rewrite of several functions? Na, not once I was told about IsLoading.

Fixed sacn settings not loading correctly at game start.

---

Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
Assets/Script/Menu/MusicLibrary/SongSearchingField.cs

Adds a key in the Music Library to set focus to the Search Bar. Suggested in Discord [here](https://discord.com/channels/1086048856678084609/1212863995103543326).

Add key to go to Search Bar.

---

Assets/Script/Integration/Sacn/SacnController.cs

“I can picture in my mind a world without war, a world without hate. And I can picture us attacking that world because they’d never expect it.” 
- Jack Handey.

Fixed some silly DMX Cue Channel bugs and auto-formatted the file.

---

Assets/Script/Menu/MusicLibrary/PopupMenu.cs

For Artist, Album, or Artist-Album, the Go To... list had way too many items. This makes it so that you only get letters in the Go To menu, just like how Song Name works now, and it goes to the first item in the list with that letter.

Improve UX for Go To menu.

---

Assets/Prefabs/Menu/Settings/SongManager/SongManagerHeader.prefab
Assets/Script/Menu/Settings/SongManager/SongManagerHeader.cs

If there is a bad songs file, it will read the first line and extract the number of errors. A button will be shown with the number of errors. Clicking on the button opens the file.
https://yarg.youtrack.cloud/issue/YARG-209/Show-error-count-after-scanning-songs-if-any-bad-songs-were-encountered

YARG-209 Show Bad Songs count on Scan

---

Assets/Script/Integration/StageKit/StageKitInterpreter.cs

Fixed programmer buffoonery

---

Assets/Script/Gameplay/GameManager.cs
Assets/Script/Integration/StageKit/StageKitHardware.cs
Assets/Script/Integration/StageKit/StageKitLighting.Cues.cs
Assets/Script/Integration/StageKit/StageKitLighting.Primitives.cs

Moved some overlooked new() calls that were not in the constructors, added venue to debug overlay, added the missing 'all' color call, fixed Dischord not direct listening.

Added current venue to debug overlay, fixed some light bugs.

---

Assets/Script/Gameplay/GameManager.cs
Assets/Script/Integration/MasterLightingGameplayMonitor.cs
Assets/Script/Integration/StageKit/StageKitLighting.Cues.cs
Assets/Script/Integration/StageKit/StageKitLighting.Primitives.cs
Assets/Script/Playback/BeatEventHandler.cs

Added count to debug overlay. formatting.

Fixed venue count on song restart

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/Gameplay/GameManager.cs
Assets/Script/Menu/Calibrator/Calibrator.cs
Assets/Script/Menu/Persistent/MusicPlayer.cs
Assets/Script/Persistent/GlobalVariables.cs
Assets/Script/Playback/SongRunner.cs
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/Settings/SettingsManager.cs
Assets/Settings/Localization/Settings Shared Data.asset
Assets/Settings/Localization/Settings_en-US.asset

There will essentially be no audio-video latency hit with the playback buffer. The only latency will be in special effects like pitch bending and overdrive.
+ Requires YARG.Core update

Add Audio Playback Buffer Customization

---

Assets/Prefabs/Menu/DifficultySelect/DifficultySelectMenu.prefab
Assets/Script/Menu/DifficultySelect/DifficultySelectMenu.cs

Re-submission of #774 to the nightly branch.

Display song info on difficulty select

---

Assets/Script/Gameplay/GameManager.Loading.cs
Assets/Script/Menu/Persistent/Toasts/Toast.cs
Assets/Script/Menu/Persistent/Toasts/ToastManager.cs

Added a way to make Toasts actionable, so that when you click on them something happens. This is optional, existing Toasts are not affected.
Also added an action on the "Rescan Required" Toast, to take the user to the Song Manager settings page.

Rescan popup action

---

Assets/Script/Integration/MasterLightingController.cs
Assets/Script/Integration/StageKit/StageKitHardware.cs
Assets/Script/Integration/StageKit/StageKitInterpreter.cs

For some reason, on linux, the stage kit doesn't shut off properly. Hopefully this fixes it.

Linux Stage Kit hang on exit fix

---

Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/Song/SongSources.cs
Assets/Script/Venue/VenueLoader.cs

Update to coincide with the YARG.Core PR that implements a FixedArray hierarchy of types.

Update For New FixedArray Hierarchy (Part 1)

---

Assets/Script/Replays/ReplayContainer.cs

Just a single function to deal with that takes a different parameter.
- Relies on the Part 3 Core PR

Use UnmanagedMemoryStreams For Reading SongCache (Part 2)

---

Assets/Script/Gameplay/HUD/Pause/GenericPause.cs
Assets/Script/Gameplay/HUD/Pause/ReplayPause.cs
Assets/Script/Gameplay/HUD/Practice/PracticeSectionMenu.cs
Assets/Script/Gameplay/HUD/SoloBox.cs
Assets/Script/Gameplay/HUD/TextNotificationQueue.cs
Assets/Script/Gameplay/HUD/TextNotifications.cs
Assets/Script/Gameplay/HUD/VocalsPlayerHUD.cs
Assets/Script/Menu/Calibrator/Calibrator.cs
Assets/Script/Menu/Common/Dialogs/ColorPickerDialog.cs
Assets/Script/Menu/Common/Dialogs/ConfirmDeleteDialog.cs
Assets/Script/Menu/Common/Dialogs/Dialog.cs
Assets/Script/Menu/Credits/CreditsMenu.cs
Assets/Script/Menu/DifficultySelect/DifficultySelectMenu.cs
Assets/Script/Menu/History/HistoryMenu.cs
Assets/Script/Menu/Main/MainMenu.cs
Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
Assets/Script/Menu/MusicLibrary/PopupMenu.cs
Assets/Script/Menu/Navigation/NavigationScheme.cs
Assets/Script/Menu/Persistent/DialogManager.cs
Assets/Script/Menu/ProfileList/ProfileListMenu.cs
Assets/Script/Menu/ProfileList/ProfileSidebar.cs
Assets/Script/Menu/ScoreScreen/ScoreScreenMenu.cs
Assets/Script/Menu/Settings/SettingsButton.cs
Assets/Script/Menu/Settings/SettingsMenu.cs
Assets/Script/Menu/Settings/Visuals/BaseSettingVisual.cs
Assets/StreamingAssets/lang/en-US.json

Added localization keys for gameplay text, dialog buttons, help bar button text, and misc dialog text.

More localization keys
