Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/DrumsTrack.cs
Assets/Script/PlayMode/FiveFretTrack.cs
Assets/Script/PlayMode/RealGuitarTrack.cs

Currently, starpower is awarded on the end of star power phrase; that is incorrect behavior, as it should be awarded on hitting the last note of the SP phrase.
TODO: test on Drums (as SP reading isn't implemented yet, verifying that currentChartIndex is being counted accurately, similarly to how it is counted on five-fret, should be enough)

Make starpower be awarded on hitting last note of phrase

---

Assets/Script/PlayMode/Play.cs
Assets/Script/UI/GameUI.cs

This fixes a bug with some tracks with incorrect song lengths in the song.ini from ending at the wrong time. It also implements the use of [end] events.

Fix songs ending at incorrect times if the ini length was wrong

---

Assets/Script/PlayMode/FiveFretTrack.cs

As the bot is set to strum on every note, this causes overstrumming with chords as the event is fired for every note in the chord, this PR fixes that by only setting strum leniency in normal play

Fix bot overstrumming after adding strum leniency

---

Assets/Scenes/MenuScene.unity
Assets/Scenes/PersistantScene.unity
Assets/Script/Constants.cs
Assets/Script/Constants.cs.meta
Assets/Script/GameManager.cs
Assets/Script/UI/MainMenu.cs
Assets/Script/UpdateChecker.cs
Assets/Script/UpdateChecker.cs.meta

Adds a check for new releases when the game launches. Version must be changed for new releases using the `MAJOR`, `MINOR` and `PATCH` integers in `Constants.cs`, and the release must be tagged in the repository matching the client version.
- Checks for updates using the GitHub releases API on startup
- Added current version next to logo on main menu
- Update notification appears on main menu when game is out of date

Add update check on startup

---

Assets/Script/PlayMode/DrumsTrack.cs

All that was done was reversing the order of the drum colors back to the original, whilst the chart is still flipped, as expected.
Fixes #56

Fix lefty flip on 4 and 5 lane drums

---

Assets/Script/PlayMode/DrumsTrack.cs

#96 did not fix the inputs, only the note colors, as DarkRTA mentioned.
I've now flipped the inputs when they're being processed as a hit, except when bot mode is on.
Fixes #56 for real this time.

Fix lefty flip drum inputs

---

ProjectSettings/ProjectSettings.asset

Somehow incremental garbage collection (Unity's default GC setting) got turned off, which causes huge lag spikes in the editor. Incremental GC spreads garbage collection over multiple frames so it doesn't pause the application for as long. This should mitigate it and from a quick test it seems to. 
Probably best to find the root cause of the large allocations though, some quick profiling showed GameManager being the place where large GC Invokes are occurring but it could be more subtle.

Re-enable incremental garbage collection

---

Assets/Script/PlayMode/FiveFretTrack.cs

After 0.8.2, strumming HO/POs caused much more overstrum than previous. This aims to fix that + some other edge cases.
TODO: fix merge conflicts

Improve HO/PO overstrum forgiveness

---

Assets/Script/PlayMode/AbstractTrack.cs

Starpower should be capped out at a full bar (1.00), however there was no check to see if the charge exceeded 1 when adding 0.25 to it after hitting a phrase.

Fix starpower going over 1

---

Assets/Script/GameManager.cs

Windows likes to explode with user names that have spaces, this should fix that. Check the comments for more details

Fixed an edge-case bug in windows path names

---

Assets/Script/UI/SelectedSongView.cs

(please someone test this on windows before)
Reference: https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest-url.html#:~:text=If%20the%20input%20URL%20starts%20with%20a%20single%20slash%20(/)%2C%20then%20the%20system%20assumes%20the%20inout%20is%20a%20path%20relative%20to%20the%20current%20domain%20on%20which%20the%20Unity%20application%20is%20running.%20On%20non%2DWebGL%20platforms%2C%20the%20system%20will%20prepend%20http%3A//localhost%20to%20the%20URL.

fix(YARG.UI): album image not loading on unix systems

---

Assets/Script/Audio/BassAudioManager.cs
Assets/Settings/Localization/Settings Shared Data.asset
Assets/Settings/Localization/Settings_en-US.asset

Fixes localisation not being added for chipmunk speedup setting (Unity didn't save it for some reason when I last PR'd), also fixes a potential memory leak by now auto freeing the source stream of a BassFX stream. Increased mixer thread count to 2 as well.

Some audio engine tweaks

---

Assets/Script/PlayMode/FiveFretTrack.cs

This makes it so sustains behave like in the original game; pressing wrong buttons drop it (unless it's a fret below a single-fret sustain), partially releasing sustains also drops it
Extended sustains are detected and their behavior is unchanged.

Fix sustain dropping

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassSampleChannel.cs
Assets/Script/Audio/Bass/BassStemChannel.cs
Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/Audio/Interfaces/IStemChannel.cs
Assets/Script/Audio/Interfaces/IStemMixer.cs
Assets/Settings/Localization/Settings_en-US.asset

Changing the volume settings for stems in the pause menu did not apply correctly when unpausing. This PR fixes this issue and changes who is responsible for applying the stem setting to the current volume (such as stem muting volumes). The stem itself is now responsible for applying the setting + volume multiplier instead of the caller
Also changed a couple localisation values for better clarity

Fix stem volume settings while paused

---

Assets/Scenes/MenuScene.unity
Assets/Script/UI/MainMenu.cs

This prevents errors from the instrument select screen expecting at least one player to be present.
A helpful indicator is provided when the button is disabled:

Disable the Quickplay button if no players are added

---

Assets/Script/GameManager.cs
Assets/Script/UI/DifficultyView.cs
Assets/Script/UI/MainMenu.cs
Assets/Script/UI/PauseMenu.cs
ProjectSettings/EditorBuildSettings.asset

Fixes:
- Calibration menu no longer breaks the game
- Difficulty numbers are now clamped properly in DifficultyView, prevents out-of-bounds index exceptions from making the instrument icons not render fully
Changes:
- Pressing back in the pause menu now resumes instead of exiting the song

Some various fixes

---

Assets/Script/PlayMode/AbstractTrack.cs

Currently, stuff such as 438/440 notes hit can lead to 100% being wrongly displayed even if not all notes were hit. This fixes that
(mfw the description is longer than the actual fix)

Fix wrong rounding for solo section percentage

---

Assets/Script/Calibrator.cs
Assets/Script/Input/DrumsInputStrategy.cs
Assets/Script/Input/FiveFretInputStrategy.cs
Assets/Script/Input/GHDrumsInputStrategy.cs
Assets/Script/Input/InputStrategy.cs
Assets/Script/Input/MicInputStrategy.cs
Assets/Script/Input/RealGuitarInputStrategy.cs
Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/DrumsTrack.cs
Assets/Script/PlayMode/FiveFretTrack.cs
Assets/Script/PlayMode/MicPlayer.cs
Assets/Script/PlayMode/RealGuitarTrack.cs
Assets/Script/UI/AddPlayer.cs
Assets/Script/UI/DifficultySelect.cs
Assets/Script/UI/MainMenu.cs
Assets/Script/UI/PauseMenu.cs
Assets/Script/UI/PlayerSection.cs
Assets/Script/UI/PostSong.cs
Assets/Script/UI/SongSelect.cs

Most aspects of input handling are now driven by `InputSystem.onEvent`. This is the first step towards FPS-independent input (this is in *no way* a comprehensive implementation for that however, just to be clear).
Input strategies are now fully event-based, and will update themselves automatically. They can be enabled and disabled as needed, which will prevent them from processing any updates. They are automatically enabled when added to the player list, and automatically disabled when removed.
Control binding and the song select menu's default keyboard navigation are also now fully event-based.
Some additional changes I made along the way:
- AddPlayer has been cleaned up quite a bit.
- Invalid microphone index value has been made into a constant.
- Input strategies now store the previous …

Basic event-based input handling

---

Assets/Script/Input/ControlBinding.cs
Assets/Script/Input/ControlBinding.cs.meta
Assets/Script/Input/DrumsInputStrategy.cs
Assets/Script/Input/FiveFretInputStrategy.cs
Assets/Script/Input/GHDrumsInputStrategy.cs
Assets/Script/Input/InputStrategy.cs
Assets/Script/Input/MicInputStrategy.cs
Assets/Script/Input/RealGuitarInputStrategy.cs
Assets/Script/Serialization/InputBindSerializer.cs
Assets/Script/UI/AddPlayer.cs
Assets/Script/UI/SongSelect.cs

Summary:
- InputStrategy now operates in terms of `InputControl<float>` rather than just `InputControl`.
- Axis inputs are now mappable as controls, and can function as either axis or button inputs.
- Currently the activation threshold for axes has a hardcoded default, needs configuration added.
- Buttons can also theoretically function as axes, though this also needs some behavior configuration as well.
- *Important note!* Some mapping strings were changed for consistency reasons, so controls previously mapped to those will need to be re-mapped.
This PR does not implement any functionality that relies on axis support, such as whammy. Wanted to split things up a bit so it's not all one big PR lol
Additional features/fixes:
- The control mapper can now detect when multiple controls have …

Rework input handling to allow for axis support

---

Assets/Script/Data/SongInfo.Sources.cs
Assets/Script/Serialization/Xbox/XboxMoggData.cs
Assets/Script/Serialization/Xbox/XboxRawfileBrowser.cs
Assets/Script/Serialization/Xbox/XboxSong.cs
Assets/Script/Serialization/Xbox/XboxSongData.cs
Assets/Script/SongLibrary.cs

-FYI, update mids aren't actually parsed in-game - you'll have to edit your midi parsing code slightly so that they are
some good logic for that: 
- if a track is in the update mid and not in the base mid, use it
- if a track is in the base mid and not in the update mid, use it
- if a track is in both the base AND update mid, go with the track in the update mid

add song update functionality

---

Assets/Script/PlayMode/DrumsTrack.cs

Fixes #173 
In the previous implementation, the lefty flip red cymbal input was being read as a regular red cymbal, which doesn't exist. 
Pro Drums lefty flip implies the player has moved the Green cymbal above the Red snare, so whilst the chart has flipped, and so have the inputs, that specific input stays the same because the input object was physically moved.

lefty flip pro drums red cymbal input fix

---

Assets/Script/PlayMode/StarDisplay.cs

Took a different approach to stop the gold star progress animation from playing.

Fix Animator warnings triggering after gold stars achieved

---

Assets/Art/Materials/PlayMode/Cymbal_Glow.mat

Fixed a bug where cymbal materials on their base weren't being displayed correctly.

Bugfix: Cymbal_Glow Material not applying correctly

---

Assets/Script/Serialization/SongIni.cs
Assets/Script/SongLibrary.cs

Previous implementation of filling the song list did skip songs without notes.mid files but whilst it did log errors about failure to parse song.ini files, it still added said broken songs to the songlist, rendering the search function unusable.
When a parsing error occurs, an exception is thrown and caught by the code that fills up the songlist and the song is skipped.
I also changed the behaviour when the "song" section isn't found in song.ini, because the song would show up as a blank entry in the songlist and break the search function too.

Skip songs with errors loading song.ini when filling the song list

---

Assets/Script/Input/DrumsInputStrategy.cs
Assets/Script/Input/GHDrumsInputStrategy.cs
Assets/Script/Input/MicInputStrategy.cs

Drums:
Vocals:
Pro Guitar navigation will come later, as I'd like to try and unify its input processing with everything else if possible.

Add missing navigation controls for drums and vocals

---

Assets/Script/Serialization/Xbox/XboxSong.cs

This fixes searching by artist being broken when a RB CON doesn't have artist information in its songs.dta file.

Turn null artist information in songs.dta into Unknown Artist

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/UI/PauseMenu.cs

Songs in CON format (that use MOGGs) would break when selecting restart as the mogg wouldn't be unloaded across scene transition. That is now fixed

Fix CONs breaking when selecting restart when paused

---

Assets/Script/PlayMode/StarScoreKeeper.cs

As the title says the rhythm and coop guitar bot were broken and this fixes it. Here's a video by Inventor211 showcasing this [bug.](https://www.youtube.com/watch?v=1NySxZCm0kE)

Fixes rhythm and coop guitar bot

---

Assets/Script/Constants.cs
Assets/Script/PlayMode/FiveFretTrack.cs

- ALLOW_DESC_GHOSTS
- Already implemented, just made into a toggle.
- ALLOW_GHOST_IF_NO_NOTES
- If the next note is outside of the timing window, do not check for ghost inputs;
- For some reason, in some rare scenarios it seems to allow ghosting when it shouldn't;
- Increasing the ALLOW_GHOST_IF_NO_NOTES_THRESHOLD variable might alleviate that;
- However if set too large, it might nullify the effect of the toggle.
- EASY_TAP_RECOVERY
- If tapping to recover combo during tap note section, skip to first valid note within the timing window. This will make it easier to recover;
- Only applies if combo is 0, and all following notes are tap notes, so it won't negatively impact FC runs.

Minor five-fret engine tweaks

---

Assets/Script/PlayMode/FiveFretTrack.cs

If a note is missed due to the combo recovery fixes, set `missedAnyNote = true;` to ensure FC ring is properly disabled.
(Includes minor refactor for some variables that didn't need to be set inside for loops)

Fix FC ring not disappearing in some cases

---

Assets/Script/Audio/AudioHelpers.cs
Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassHelpers.cs
Assets/Script/Audio/Bass/BassHelpers.cs.meta
Assets/Script/Audio/Bass/BassMoggStem.cs
Assets/Script/Audio/Bass/BassStemChannel.cs
Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/PlayMode/FiveFretTrack.cs
Assets/Script/PlayMode/Play.cs

Got a couple complaints that the reverb on star power is extremely bad on single stem songs, that's because it previously reverbed the whole channel and also applied gain. I've made some changes to that:
- Split stems into 2 channels, original channel and reverb channel.
- Apply an EQ to wipe out the bass frequencies and lower the lower mid frequencies of the reverb channel.
- Boost the higher mid/treble frequencies in the reverb channel slightly.
- Reverb the new channel with majority wet mix and very little dry mix.
- Play the reverb channel at 70% volume of the regular channel when star power is active.
- Mute the reverb channel when star power is inactive.
These changes prevent bass frequencies from being reverbed and sounding really bad. It also makes the audio sound brighter without …

Overhaul Star Power FX

---

Assets/Prefabs/UI/BindingButton.prefab
Assets/Prefabs/UI/BindingButton.prefab.meta
Assets/Scenes/MenuScene.unity
Assets/Script/Input/ControlBinding.cs
Assets/Script/Input/FiveFretInputStrategy.cs
Assets/Script/Input/InputStrategy.cs
Assets/Script/Serialization/InputBindSerializer.cs
Assets/Script/UI/AddPlayer.cs

This allows for overstrumming, overtapping, and other flickering button inputs to get masked out during a certain time period after a button binding's state changes. It can be configured per-binding, with a range of 0-100 ms.
Some notes:
- Only same-direction overstrumming will be debounced, strum up and down are configured to override each others' debounce timers in order to still allow raking.
- **Mappings will be reset due to this change.** I didn't bother with trying to avoid this since it's really no big deal to re-do them, not really worth the time to prevent it.
My testing for this has been fairly minimal so it may need some changes in the future, but I've ensured that everything works as would be expected.

Implement debouncing for button inputs

---

Assets/Script/PlayMode/ScoreDisplay.cs
Assets/Script/PlayMode/ScoreKeeper.cs
Assets/Script/PlayMode/StarDisplay.cs

Simple UI logic: if MicPlayer.Instance is null, move ScoreDisplay up. Otherwise stay.
As an aside, moved ScoreKeeper into the PlayMode namespace.

Move ScoreDisplay when MicPlayer isn't present

---

Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/FiveFretTrack.cs

Maybe I shouldn't do multiple things in a single commit lol
- Note count fix
- Chords were treated as separate notes when counting, so the total note count, the notes hit count (and as a result, the note missed count) were inaccurate (i.e. Soulless 3 has 4066 notes instead of 3999);
- Solo note count, albeit done separately, suffered from the same issue, which was also fixed.
- Solo reset fix*
- Solo is now reset in the part of the code that starts it/shows its results;
- **ADJACENT SOLOS ARE STILL BROKEN!** Solo region start/end will need to be reworked for this to be solved, which is not the goal of this PR.
- Slightly easier tap recovery
- Removed `pressedThisFrame` check in FiveFretTrack.cs line 298 to allow tap recovery by doing pull-offs rather than just button presses.

Note count fix, solo reset fix*, slightly easier tap recovery

---

Assets/Script/Input/ControlBinding.cs

Strumming was a little funky, fixed it by making debounce overrides only take effect if debounce is enabled on the control and the timer is running.

Debounce hotfix

---

Assets/Script/PlayMode/FiveFretTrack.cs

That line would cause issues in sequences with lots of taps of the same fret (i.e. Charmeleon Carneval (Andromeda Solo Medley chart)) while not fixing any real problems

minor overstrum-related fix

---

Assets/Script/PlayMode/ScoreKeeper.cs

Adjusted solo bonus scoring minimum to be at 60% instead of 50%.
Addresses #227

Fix bonus solo points being awarded when solo completion is MESSY (50-59%)

---

Assets/Script/ThirdParty/DiscordController.cs

- Using Play.Instance.SongTime to calculate the time left of the song;
- Removed unused variables;
- Add code for a future implementation

Fix Discord Unpause Timer

---

Assets/Script/PlayMode/FiveFretTrack.cs

Makes it so GetNoteCount() for five-fret fetches the correct amount of notes, and as such, shows the correct percentage / result of misses on the ending screen
Also removes unused variables

Note count fix

---

Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/PlayMode/Play.cs
Assets/Script/Serialization/Xbox/XboxImage.cs
Assets/Script/Serialization/Xbox/XboxMoggData.cs
Assets/Script/Song/CacheHelpers.cs
Assets/Script/Song/CacheHelpers.cs.meta
Assets/Script/Song/ScanHelpers.cs
Assets/Script/Song/SongCache.cs

CON data is cached now as well as part difficulties

Added extracted CON read/write for song cache

---

Assets/Script/PlayMode/StarScoreKeeper.cs

Due to a player with no part having NaN stars (divide by 0 notes)

Fix stars being stuck at 1 for players with no part

---

Assets/Script/Chart/Loaders/FiveLaneDrumsChartLoader.cs
Assets/Script/Chart/Loaders/FiveLaneDrumsChartLoader.cs.meta
Assets/Script/Chart/Loaders/FourLaneDrumsChartLoader.cs
Assets/Script/Chart/Loaders/FourLaneDrumsChartLoader.cs.meta
Assets/Script/Chart/Loaders/GuitarChartLoader.cs
Assets/Script/Chart/Loaders/IChartLoader.cs
Assets/Script/Chart/Loaders/New/NewDrumChartLoader.cs
Assets/Script/Chart/Loaders/New/NewGuitarChartLoader.cs
Assets/Script/Data/YargChart.cs

Currently only notes loading is implemented. Converting between 4-lane and 5-lane does not work properly currently, I've left this as a todo since it'll require some restructuring that I don't wanna deal with in this PR.

Implement basic .chart drums loading

---

Assets/Script/Data/Difficulty.cs
Assets/Script/Song/Preparsers.meta
Assets/Script/Song/Preparsers/ChartPreparser.cs
Assets/Script/Song/Preparsers/ChartPreparser.cs.meta
Assets/Script/Song/Scanning/SongScanThread.cs
Assets/Script/Song/SongCache.cs
Assets/Script/Song/Types/SongEntry.cs
Assets/Script/UI/DifficultySelect.cs

Reads .chart files when scanning and determines what instruments and difficulties are available and caches them. Converted difficulty select UI to only display available parts

.chart Preparsing

---

Assets/Script/DtxCs/DTX.cs

The DtxCS DTA parser included a check for ending brackets in the middle of symbol parsing, breaking parsing of certain songs that included brackets in their shortnames.
I can't immediately tell any reason for this being here as it breaks the flow of the parser when the case is hit (the next `'` that is hit at the end of the symbol causes a new symbol to begin, causing the "whitespace encountered in symbol error"), but it *could* break other songs. Might be worth testing on a large library before merging.

(maybe) fix issue with dta files containing brackets in symbols

---

Assets/Script/PlayMode/FiveFretTrack.cs

Only apply Zoidberg multi-hit leniency if last note was a strum, rather than if last input was a strum
More info in "Strumming Taps notes will cause other taps to be hit" Discord help thread

fix taps/hopos self-hitting in wrong situations

---

Assets/Script/Constants.cs

Sometimes it would allow more ghosts than it should; that's because (at the time I didn't realize this) the hit window is actually `2 * Constants.HIT_MARGIN`. Setting the threshold var to 2 solved this issue.

Minor ALLOW_GHOST_IF_NO_NOTES fix

---

Assets/Script/Data/GenericLyricInfo.cs
Assets/Script/PlayMode/Play.cs
Assets/Script/Serialization/Parser/MidiParser.Vocals.cs

Changes:
- Parse phrase length and ignore empty phrases from midi for generic vox
- Clear generic vocal phrase in UI after phrase ends
Addresses #228

Clear phrase after ending for generic vox

---

Assets/Script/LoadingManager.cs
Assets/Script/Song/SongContainer.cs

Changes how caches are full scanned on startup, previously they were queued individually which prevents any parallel scanning. Adjusted it so that they are passed all at once and can be threaded properly

Fix caches not being scanned in parallel on error

---

Assets/Prefabs/UI/ScoreDisplay/ScoreDisplay.prefab

Slightly decrease the alpha of the top bar to better blend it in with the GS progress sprite.

Gold star progress graphic tweak

---

Assets/Script/Song/Preparsers/ChartPreparser.cs
Assets/Script/Song/Preparsers/MidPreparser.cs
Assets/Script/Song/ScanHelpers.cs
Assets/Script/Song/Scanning/SongScanThread.cs
Assets/Script/Song/Scanning/SongScanner.cs

Found some very odd songs and charts which broke the preparser entirely so added some exception handling with a CorruptedNotesFile result to handle these cases now.

Handle some exceptions with chart preparsing

---

Assets/Script/Serialization/Xbox/MoggBassInfoGenerator.cs
Assets/Script/Serialization/Xbox/XboxCONFileBrowser.cs
Assets/Script/Serialization/Xbox/XboxRawfileBrowser.cs
Assets/Script/Serialization/Xbox/XboxSongUpdateBrowser.cs
Assets/Script/Song/Scanning/SongScanThread.cs

When applying song updates, you no longer require all updates for a particular shortname to be contained a singular data array. You can now have as many data arrays with the same shortname as you like!

added support for multiple shortname song arrays in songs_updates.dta

---

Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayerManager.cs
Assets/Script/UI/PlayResultScreen/PlayerCard.cs

* Added a `MaxCombo` variable to `AbstractTrack` and  `PlayerManager.LastScore`.
* The max combo is now displayed on the results screen.

Implement max combo on results screen

---

Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/FiveFretTrack.cs

These are playable on CH; I've made it so the open note hit detection ignores held sustains if it's an extended sustain
(why do charters do this, though?)
Edit: this also fixes total solo note count not resetting between solos

Open extended sustain fix

---

Assets/Script/UI/MusicLibrary/Sidebar.cs

Sources was reporting i.genre instead of i.source

Small typo update to Sidebar.cs

---

Assets/Script/Audio/AudioHelpers.cs
Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassHelpers.cs
Assets/Script/Audio/Bass/BassMoggStem.cs
Assets/Script/Audio/Bass/BassStemChannel.cs
Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/Audio/Interfaces/IStemChannel.cs
Assets/Script/Audio/Interfaces/IStemMixer.cs
Assets/Script/Constants.cs
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/Settings/SettingsManager.cs
Assets/Script/UI/MainMenu.cs
Assets/Script/UI/MusicLibrary/SongSelection.cs
Assets/Settings/Localization/Settings Shared Data.asset
Assets/Settings/Localization/Settings_en-US.asset

- Configured 30s preview duration & shorter fade-in time
- Added Preview Volume Button to Settings (25% by default)
- Added max volume parameter to FadeIn function
- Made FadeOut function a UniTask that runs until all playing stems are fully muted
- Disable crowd stem when previewing audio from ini file
- Disable crowd stem when previewing audio from con file
- Added functions for start & stopping preview audio (with looping mechanic at Start function)

Added Song Preview to Music Library

---

Assets/Scenes/PersistantScene.unity
Assets/Script/GameManager.cs
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/UI/FpsCounter.cs

Replace the Green FPS counter and Memory status with the new one. When in Editor the counter will be Persistent even if you disable from settings
[Changed]
- Update the layout of the components at PersistantScene
- Update the Settings Callback to enable always in Editor to override the settings
- Commented the Old GUIUpdate function
- Added the Memory code in FpsCounter.cs

Update FPS Counter with Memory status Now

---

Assets/Script/GameManager.cs
Assets/Script/Input/InputStrategy.cs
Assets/Script/Input/RealGuitarInputStrategy.cs
Assets/Script/Input/StageKitHapticsManager.cs
Assets/Script/Input/StageKitHapticsManager.cs.meta
Packages/manifest.json
Packages/packages-lock.json

This version brings support for Rock Band stage kits and sanjay900's new firmware. Some scaffolding code has been added for the haptics these devices support.
This version also adds a bunch of convenience APIs for retrieving controls by index or enum (which I switched the Pro Guitar input strategy over to), as well as hopefully support for the World Tour slider bar.

Update PlasticBand-Unity to v0.3.0

---

Assets/Script/Serialization/Xbox/XboxSTFS.cs

The seemingly biggest bottleneck resided in the lack of optimization for contiguous blocks of data. Prior, for every block, a new filestream would be opened, a new offset would be calculated, and a new array the size of the block would be created and then copied.
The change here was to immediately read into the data byte array in chunks (if contiguous). Should provide an immense speedup.

Improve CON parsing speed

---

Assets/Script/PlayMode/FiveFretTrack.cs

Currently, the "strum to recover combo" wasn't respecting the strum leniency. This causes the wrong note to be detected as strummed in some scenarios (skipping to the next note, instead of waiting for the strum leniency to end).
This fix makes it so, if there's an ongoing combo, it waits for the strum leniency to end before triggering the "combo recovery strum" code (by which point it would've been an overstrum already).
~~(This has _not_ been thoroughly tested, so some additional testing to see if strumming feels better would be helpful!)~~
Edit: Tested by other players, who confirm this indeed makes it better to play certain strumming sections

Make combo-recovery-strum not break existing combo

---

Assets/Scenes/MenuScene.unity
Assets/Script/Input/MicInputStrategy.cs
Assets/Script/PlayMode/MicPlayer.cs
Assets/Script/UI/AddPlayer.cs

Cleaned up AddPlayer a little along the way as well.
When selecting a microphone, you are now prompted to select a navigation device, with an option to go with no device. This fixes the issue of no device being available when binding was being started, so now the bindings menu can be shown correctly. I also added additional bindings for menu shortcuts 2 and 3, and implemented pausing into MicPlayer.
In addition, I've also reworked the input strategy selection list so that vocals is only ever shown (and is the only option available) when a microphone is selected. Can't even play vocals with only a guitar lol, no point in showing it.

Fix mic navigation and only allow selecting vocals mode when a microphone is selected

---

Packages/manifest.json
Packages/packages-lock.json

Another Unity moment, HID Santroller device support is causing the same crashes that PS4 instrument support does :/
Other changes:
- Fixed some initialization issues when entering Play mode in the editor
- Fixed XInput layout overrides not being evaluated correctly due to a logic error

Update PlasticBand-Unity to v0.3.1

---

.vscode/settings.json

I keep finding myself temporarily un-hiding the Library folder to look into something the input system or some other package is doing, got tired of it so here's this lol
Included ProjectSettings too because might as well, it's tracked by git and doesn't really harm much to unhide.

Remove Library and ProjectSettings folders from VS Code file exclude settings

---

Assets/Script/Audio/Bass/BassPreviewContext.cs

- The preview start time somtimes won't be set based off the `_songToLoad` preview start time. Fixed that!
- Made sure that `_songToLoad` variable isn't set to null

Song Preview Fixes Pt. 3

---

Assets/Scenes/PersistantScene.unity
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/Song/SongCache.cs
Assets/Script/ThirdParty/UpdateChecker.cs
Assets/Script/UI/DevWatermark.cs
Assets/Script/UI/FpsCounter.cs
Assets/Script/UI/ToastManager.cs

- ToastManager:
- Move into the YARG.UI namespace
- Reformat the file
- Re-ordered a couple things 
- Use `displayName` instead of `name` when toasting device connections/disconnections
- DevWatermark:
- Move into the YARG.UI namespace
- Remove unused using directives
- Remove 'disabled' log message
- FpsCounter:
- Move into the YARG.UI namespace
- Serialize color values and update rate instead of hard-coding them
- Remove UpdateSettings and replace calls to it with calls to SetVisible

Some quick UI-related code cleanups

---

Assets/Script/UI/MusicLibrary/SongSelection.cs

* Added navigation button (Blue) "Next section" that selects the next letter with respect to the current song.
* Navigation button (Orange) is added to select a random song.

Added navigation buttons "Next section" and "Random song"

---

Assets/Scenes/PlayScene.unity

See help thread here - https://discord.com/channels/1086048856678084609/1112580999411408997/1112580999411408997
previously, the bg videos were rendered via render texture, which caused very odd artifacting in some cases, namely webm.
This PR changes that to render to the camera far plane instead, which fixed the artifacting

render bg video to camera not render texture

---

Assets/Script/UI/MusicLibrary/Sidebar.cs
Assets/Script/Util/RichTextUtils.cs
Assets/Script/Util/RichTextUtils.cs.meta
Assets/Script/Util/Utils.cs

Some strings such as loading phrases can contain Unity/TMP rich text tags and some of those tags break sizing or other constraints such as offsets.
Currently it is only implemented on the help bar for loading phrases when using the music library. Should be applied to other places where necessary
- Added a couple utility functions which strip rich text tags.
- Can specify which rich text tags to remove, or which to keep.
- Uses regex and caches regex objects to be faster after first use.

Strip rich text tags from strings to prevent text issues

---

Assets/Script/Data/YargChart.cs
Assets/Script/PlayMode/Play.cs
Assets/Script/Serialization/Parser/MidiParser.cs

Global events are now parsed from both .chart and .mid files in order to allow accounting for the `[end]` event when determining song length.
In addition, song loading now ensures that the song length will never be smaller than the time of the last note in the chart, and a small delay of 2 seconds is added on to the length after both `[end]` event and last-note handling to prevent songs that have no trailing silence from ending instantly.
Also had to make a fix to YargChart since some properties weren't being initialized with .chart files, and would cause errors with these changes.

Some song length/end fixes and QoL changes

---

Assets/Script/PlayMode/AbstractTrack.cs

This PR has no sustain SP gain, only the 32-beat calculation for drain.

Beats-based SP drain only

---

Assets/Script/Constants.cs
Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/FiveFretTrack.cs

Somehow we ended up with a system that made it dead-easy to split the timing for the front and back of the hit window lol, if we ever wanna experiment with that we now can.

Fix hit window not scaling correctly to different song speeds; allow asymmetrical hit windows

---

Assets/Script/PlayMode/DrumsTrack.cs

* On drums, only one note in a chord will now be converted to an activator.
* Cymbals are preferred first.  If a chord does not contain any cymbals, a pad will be chosen instead.
* In the event that only a kick note is present, it will become the activator.

Only one note in a chord can be an activator

---

Assets/Script/UI/MusicLibrary/SongSelection.cs

Small improvement on the current song navigation:
- Red button now goes back to the top of the list if there is no search filter active (allows to get back to the top and select "Random" or "Recommended"
- Yellow button now changes the sort order between song name (default), artist name, and source name.
- Blue button filters on artist if no filter is set, and a second press filters on source instead.
Could be improved:
- Text for navigation menu does not change (I would like to switch it to "Select Source", or "Back to Top")
- Orange button for selecting next section works for song name and artist name, but is broken on source name (it tries to get to the bottom of the list every time, it could be due to the fact that some sources are empty)

Add sorting and ordering on blue and yellow frets

---

Assets/Script/PlayMode/FiveFretTrack.cs

The issue with SP being whammyable from the end of the last phrase to the end of the song is still here, but now limited to sustains only, as is the issue where a sustain on the note that awards an SP phrase is not whammyable.

Check for held sustains before giving starpower

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/UI/AddPlayer.cs

Some microphones were not getting listed due to their BASS device type not being Microphone. Now instead of checking for the device type, only devices specified as loopback devices by BASS are excluded.
The "Default" device entry has also been excluded, instead the default microphone is marked as such in the device list:

Fix some issues with listing microphones in the device list

---

Assets/Script/Song/BooleanConverter.cs
Assets/Script/Song/BooleanConverter.cs.meta
Assets/Script/Song/Preparsers/MidPreparser.cs
Assets/Script/Song/SongCache.cs
Assets/Script/Song/Types/IniSongEntry.cs
Assets/Script/UI/DifficultySelect.cs

Parsing of boolean values in song.ini files is now handled through a BooleanConverter, rather than manually checking the string values. Since there's no regulation of how these are written, they can show up as a variety of things (e.x. `true`, `False`, `1`), which the new converter accounts for correctly.
Harmonies was never checked for explicitly in chart files, causing issues when a song didn't have them charted. The presence of harmonies is now cached and checked for correctly, so it will no longer be selectable if it is no longer charted.

Fix some parsing and caching issues

---

Assets/Art/UI/TextGradient_Gold.asset
Assets/Art/UI/TextGradient_Gold.asset.meta
Assets/Art/UI/TextGradient_Red.asset
Assets/Art/UI/TextGradient_Red.asset.meta
Assets/Art/UI/TextGradient_Silver.asset
Assets/Art/UI/TextGradient_Silver.asset.meta
Assets/Prefabs/UI/TrackView.prefab
Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/StarScoreKeeper.cs
Assets/Script/UI/TrackView.cs

Summary:
- Solo phrases now have their note counts pre-calculated, and are now excluded if they contain no notes (overdrive phrases are also now excluded if they have no notes).
- All text creation related to the solo box has been moved to TrackView, rather than the methods there accepting strings they take the actual values and turn those into strings themselves.
- The solo score bonus has been re-added, along with displaying it after a solo.
- The solo textbox is now colored again using the vertex colors that were present in the previous implementation. This time they've been turned into asset files, and can now be used on any other textbox if desired.
- The previously commented-out code has been removed now that it's fully reimplemented.
- Solos now wait for their first note to be the …

Reimplement, reorganize, and fix a number of solo handling things

---

Assets/Script/Chart/BeatHandler.cs

In cases where charts finish with in a 1/x time signature (where x > 4) the beat generation code falls into an infinite loop trying to finish the song on a measure. This was impossible though as 1/x time signatures are forced to only generate the first measure as a measure line, while the rest are standard strong/weak beats.
This caused an infinite loop and generated beats until memory ran out causing the game to hang forever.
Thanks to JasonParadise for finding this bug on stream and sending me the chart to diagnose the problem.

Fix infinite loop generating beatlines in 1/x time signatures

---

Assets/Scenes/PersistantScene.unity
Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/Audio/Interfaces/IStemChannel.cs
Assets/Script/Audio/Interfaces/IStemMixer.cs
Assets/Script/PlayMode/Play.cs
Assets/Script/UnityMainThreadCallback.cs
Assets/Script/UnityMainThreadCallback.cs.meta

Some songs (presumably with corrupt audio files) have reported lengths longer than BASS can play. Therefore the song's position never reached the supposed length and the gameplay never ended.
Instead of using the song position, it now uses SYNC events in BASS with callbacks. Probably not done in the nicest way but it did work in quick testing. Might need more testing.

Fix songs not ending in rare cases

---

Assets/Prefabs/DrumsTrack.prefab

At some point the hit window object on the drums track got moved a little ways behind where it was supposed to be, resulting in the hit window visually being longer in the back and shorter in the front despite not actually functioning that way.

Fix drums hit window visual not being centered correctly

---

Assets/Scenes/PersistantScene.unity
Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassMoggStemChannel.cs
Assets/Script/Audio/Bass/BassStemChannel.cs
Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/Audio/Interfaces/IStemChannel.cs
Assets/Script/Audio/Interfaces/IStemMixer.cs
Assets/Script/PlayMode/Play.cs
Assets/Script/UnityMainThreadCallback.cs
Assets/Script/UnityMainThreadCallback.cs.meta

Let's try this again, shall we?
From the original PR:
> Some songs (presumably with corrupt audio files) have reported lengths longer than BASS can play. Therefore the song's position never reached the supposed length and the gameplay never ended.
>
> Instead of using the song position, it now uses SYNC events in BASS with callbacks. Probably not done in the nicest way but it did work in quick testing.
I have verified that the song that had issues reported ends correctly, and that other songs (including both .ini and CON songs) also end correctly.

Fix songs not ending in rare cases, take 2

---

Assets/Scenes/PersistantScene.unity
Assets/Script/UI/FpsCounter.cs

[FPS Counter]
- The Memory Text is in one line now:  
**FPS:** 12345   •   **Memory:** 12345mb
- Red dot if FPS lower than 30, yellow if lower than screen refresh rate, green otherwise
[PersistantScene]
- Fix the Position of Info Container and height
- Lower the text size since the Scene is render at 1080p now
- add transparency to the Watermark

Info Container Fix

---

Assets/Script/Input/FiveFretInputStrategy.cs

Tilt is set as a button, since PS2 guitars have a tilt button rather than a whole axis.

Add tilt mapping to FiveFretInputStrategy

---

Assets/Script/PlayMode/AbstractTrack.cs
Assets/Script/PlayMode/DrumsTrack.cs
Assets/Script/PlayMode/FiveFretTrack.cs

New code stops combo breaks before the chart starts and after the code ends. (All credit for that goes to TheNathannator/drumbs, I just kinda put it together)
Works for both 5 Fret Guitar and Drums, hasn't yet been implemented into Real Guitar.
This code will be reused later for Freestyle Drums, however I haven't yet committed any of that since it's using non-original sound effects for the time being. Once I can get original samples, either by myself or through someone on the server, I'll start pushing the code for that.

No Overstrum Before/After Chart. Drum Freestyle soon to come.

---

Assets/Art/UI/MusicLibrary/Chevron_Down.png
Assets/Art/UI/MusicLibrary/Chevron_Down.png.meta
Assets/Script/Song/SongSearching.cs
Assets/Script/Song/SongSearching.cs.meta
Assets/Script/Song/SongSorting.cs
Assets/Script/UI/MusicLibrary/SongSelection.cs
Assets/Settings/AddressableAssetsData/AssetGroups/Default Local Group.asset

* Headers are only shown if the song list is greater than 30 songs (arbritrary number)
+ TODO: Tweak constant MIN_SONGS_FOR_SECTION_HEADERS
* Added filters to search for songs without a specific instrument 
+ instrument:-guitar 
+ instrument:-bass 
+ instrument:-drums 
+ instrument:-keys 
+ instrument:-vocals 
+ instrument:-band
* The search results are merged
+ source:rb1dlc;source:rb2dlc
* Fixed bug that displayed the following filter incorrectly if the back button was pressed
* SongSelection.cs class refactored
+ SongSearching.cs created

Headers are added for the different sections, merged results, filter for songs without certain instruments

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassMicDevice.cs

Fixes the `ExecutionEngineException: String conversion error: Illegal byte sequence encounted in the input.` exception. By default on Windows, BASS will retrieve device names in ANSI, even if they are Unicode names (other platforms always use Unicode). BASS has a config option to use Unicode on Windows so I enabled that.
Changed the device list to use a whitelist of types instead of including all non-loopback devices. The list may not be completely exhaustive yet but it excludes most devices which aren't recording devices.
Fixed the `SampleFormat` error when trying to initialise a microphone (particularly on Linux). I believe this is caused by Linux/devices on Linux not supporting floating point sample recording. Instead it now uses standard 16-bit samples and does the floating point …

Various Microphone/Vocals fixes

---

Assets/Script/Obsolete/Data/YargChart.cs
Assets/Script/Track/AbstractTrack.cs
Assets/Script/Track/DrumsTrack.cs
Assets/Script/Track/FiveFretTrack.cs

Solos not having their note count set correctly was an error on my part lol, got the track check inverted. Drums also just did not keep track of how many notes were hit during solos, so I threw that in too.
SP/solos/activations not showing up was an oversight from a check that prevents events from being loaded for the same track twice, this has been addressed.

Properly fix solos, and fix Pro Drums/5-lane drums SP/solos/activations not showing up

---

Assets/Script/Obsolete/Serialization/Xbox/MoggBassInfoGenerator.cs

Utilizing trig identities
https://proofwiki.org/wiki/Cosine_of_x_minus_Sine_of_x/Cosine_Form
https://proofwiki.org/wiki/Sine_of_x_plus_Cosine_of_x/Sine_Form

Remove redundant calculation in BASS matrix generation

---

Assets/Script/ThirdParty/UpdateChecker.cs

Fixes 404 not found error when trying to test play in unity when it checks for game updates. If you open the old URL in a browser, itl also do an error 404 not found. Not entirely sure why this hasnt been changed (?)

Fix 404 not found error

---

Assets/Script/Menu/MainMenu.cs
Assets/Script/Menu/Socials.cs
README.md

While normally the links would be redirected automatically, since EliteAsian123/YARG does exist now, the redirect no longer works.

Fix GitHub links leading to the wrong page

---

Assets/Script/Gameplay/BeatEventManager.cs

Previously, when subscribing to BeatEventManger after the song started, the action would fire a billion times in a second to catch up to the current song tick, now it calculates and adds whatever was missed before subscribing.

Fixed race condition on beat subscribe

---

Assets/Script/Gameplay/BeatEventManager.cs

Add and remove states from the _state list outside the main loop to prevent enumeration errors. (aka removing things from the list while it loops)

Fixed potential enumeration problem in foreach loop

---

Assets/Scenes/Gameplay.unity
Assets/Script/Gameplay/BeatEventManager.cs.meta
Assets/Script/Gameplay/GameManager.cs
Assets/Script/Gameplay/Player/TrackPlayer.cs
Assets/Script/Integration/StageKit/StageKitGameplay.cs
Assets/Script/Integration/StageKit/StageKitLighting.Cues.cs
Assets/Script/Integration/StageKit/StageKitLighting.Primitives.cs
Assets/Script/Playback.meta
Assets/Script/Playback/BeatEventHandler.cs
Assets/Script/Playback/BeatEventHandler.cs.meta
Assets/Script/Playback/SongRunner.cs
Assets/Script/Playback/SongRunner.cs.meta

Did this in preparation for the calibrator redo I'm planning, so that no song playback code needs to be duplicated between it and gameplay.
While I was at it, I adjusted the beat event handler a little bit:
- The `BeatEventHandler.Info` struct should be a little more intuitive to set and use, everything is now relative to a single beat instead of four.
- The doc comments now clarify that the beat rate is relative to the current time signature's denominator, rather than absolute.
- The current tempo is now tracked in order to speed up `TickToTime`, as now the binary search can be skipped and the time calculated directly.

Split out song playback and beat event handling into reusable classes

---

Assets/Script/Gameplay/BackgroundManager.cs
Assets/Script/Gameplay/GameManager.cs
Assets/Script/Gameplay/HUD/Practice/PracticeSectionMenu.cs
Assets/Script/Gameplay/PracticeManager.cs
Assets/Script/Playback/SongRunner.cs
Assets/Script/Venue/VenueLoader.cs

Was very satisfying to load up TWO-TORIAL and have its video background start right on the drop 40 seconds in lol
Notable changes:
- The struct returned by the venue loader has been refactored to both have a better name and indicate where a venue was sourced from, as we don't want to apply video start/end times to a global video.
- BackgroundManager now only `Update()`s when a video is being played, and its update loop has been refactored to implement video start/end time. When it no longer needs to update, it disables itself.
- Song videos will loop if they are notably shorter than the song itself. The threshold is 85% of the song's length: below that it will loop, equal to or above it won't. All other videos will always loop.
- Song videos now follow the song speed and are seeked when …

Improve handling of song-specific video backgrounds

---

Assets/Prefabs/Menu/DifficultySelect/DifficultySelectMenu.prefab
Assets/Script/Helpers/LocaleHelper.cs
Assets/Script/Menu/Common/Header/HeaderTabs.cs
Assets/Script/Menu/Navigation/NavigatableBehaviour.cs
Assets/Script/Menu/Navigation/NavigationGroup.cs
Assets/Script/Menu/Navigation/NavigationTextColorizer.cs
Assets/Script/Menu/Navigation/ScrollViewNavigationUpdater.cs
Assets/Script/Menu/ProfileList/ProfileView.cs
Assets/Script/Menu/Settings/SettingsMenu.cs

Navigatables are now selected using an index instead of a direct reference, which helps to ensure various things about how selections are handled. Deselections are also now reported via the selection changed event, and more error checking/reporting has been added to detect issues such as out-of-range indexes and duplicate entries.
In addition, this PR fixes the song path manager throwing an out-of-range exception when refreshing the settings menu, as well as the unintentional wraparound that would happen in the difficulty menu when scrolling down on Ready.

Clean up navigation group selection handling and fix various issues

---

Assets/Script/Menu/Navigation/NavigatableBehaviour.cs

When the mouse was positioned on top of a menu option that appeared, it was automatically selected, which is annoying when using an instrument as the main input device

Fix idle mouse causing wrong initial selection of menu options

---

Assets/Art/Menu/MainMenu/SelectionHighlight.png
Assets/Prefabs/Menu/MainMenu/MainMenu.prefab
Assets/Prefabs/Menu/MainMenu/MenuBadge.prefab

Added text color to main menu on selection using the NavigationTextColorizer script and changed selection highlight PNG to white so that the color can be selected in the unity editor.
Updated PR:
- Changed history color back to yellow.
- Updated all colors to follow YARG design standards.
[PREVIEW IMAGES]

Main menu colored text highlight.

---

Assets/Script/Gameplay/GameManager.cs
Assets/Script/Gameplay/HUD/InputViewer/InputViewerButton.cs
Assets/Script/Gameplay/HUD/LyricBar.cs
Assets/Script/Gameplay/HUD/Practice/PracticeHud.cs
Assets/Script/Gameplay/HUD/ScoreBox/ScoreBox.cs
Assets/Script/Gameplay/HUD/SoloBox.cs
Assets/Script/Gameplay/HUD/VocalsPlayerHUD.cs
Assets/Script/Gameplay/Visuals/ComboMeter.cs
Assets/Script/Menu/Persistent/StatsManager.cs
Packages/manifest.json
Packages/packages-lock.json
ProjectSettings/PackageManagerSettings.asset

Remembered about the existence of [ZString](https://github.com/Cysharp/ZString) and realized we don't have to write custom text formatting to avoid allocations anymore lol
This should help reduce the amount of stuttering that might happen every so often, allocation rates during gameplay are noticeably reduced (100 KB/s -> 60 KB/s). There's still other allocations to track down, but this is a good start for now.
These changes will unfortunately not reflect in the editor due to TextMeshPro always updating the internal string instance when in the editor, which is done to keep the inspector up to date:

Use ZString package for formatting text to text boxes in gameplay

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassHelpers.cs
Assets/Script/Audio/Bass/BassStemChannel.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/Gameplay/GameManager.Audio.cs
Assets/Script/Gameplay/Player/BasePlayer.cs
Assets/Script/Gameplay/Player/DrumsPlayer.cs
Assets/Script/Gameplay/Player/FiveFretPlayer.cs
Assets/Script/Gameplay/Player/TrackPlayer.cs
Assets/Script/Gameplay/Player/VocalsPlayer.cs

Reintroduces a couple of things that existed prior to the rewrite.
- Star Power reverb is back (and adjusted slightly)
- Note miss sound effect is back
- Fix some issues with stem muting and refactored the code
- Added definitions and code to play Overstrum SFX (sound files still need to be finalised and added)
Includes a YARG.Core update for the overstrum sample definitions

Re-implement various sound effects from v0.11

---

Assets/Script/Audio/Bass/BassAudioManager.cs
Assets/Script/Audio/Bass/BassStemMixer.cs
Assets/Script/Audio/Interfaces/IAudioManager.cs
Assets/Script/Audio/Interfaces/IStemMixer.cs

To make game objects or particles in the background scene react to the sound being played, the Bass.ChannelGetData call had to be created in the BassStemMixer to extract the audio data from the stems. 
Audio visualizers are able to be created in the future with this get data call extended in as shown below.
https://github.com/YARC-Official/YARG/assets/25489150/5186da67-3c23-415c-8ab3-eedde59605b9

Added Bass.ChannelGetData call to Stem Mixer

---

Assets/Prefabs/Menu/ProfileInfo/EditBinds/BindGroups/ButtonBindGroup.prefab
Assets/Prefabs/Menu/ProfileInfo/EditBinds/SingleBindViews/SingleButtonBindView.prefab
Assets/Prefabs/Menu/ProfileInfo/EditBinds/SingleBindViews/SingleMidiNoteBindView.prefab
Assets/Script/Input/Bindings/AxisBinding.cs
Assets/Script/Input/Bindings/ButtonBinding.cs
Assets/Script/Input/Bindings/ControlBinding.cs
Assets/Script/Input/Bindings/DebounceTimer.cs
Assets/Script/Input/Bindings/IndividualButtonBinding.cs
Assets/Script/Menu/ProfileInfo/EditBinds/BindGroups/ButtonBindGroup.cs
Assets/Script/Menu/ProfileInfo/EditBinds/SingleBindViews/SingleButtonBindView.cs
Assets/Script/Menu/ProfileInfo/EditBinds/SingleBindViews/SingleMidiNoteBindView.cs

Things were *very* busted in here lol, debounce should no longer be causing overhitting or incorrectly eating inputs.
Additionally, the raw value display for button bindings has been removed. It was too much of a hassle to get working right with debounce, and there will almost never be any perceivable difference between it and the normal value display. Only the calibrated value display remains.

Various debounce reworks and fixes

---

Assets/Script/Gameplay/GameManager.Loading.cs
Assets/Script/Settings/VenueAutoGenerationPreset.cs

This PR autogenerates the aforementioned FogOn/FogOff events; it happens before the venue lighting autogeneration, since the venue might be authored but still not have any fog events.
Tested by @TheFatBastid

Auto-generate fog events if there are none

---

Assets/Settings/Localization/Main_en-US.asset

Kinda bugged me to see `"Album - Artist"` in the sort list instead of just `Album - Artist`.
As far as I can tell, this doesn't have any adverse affects, but someone more familiar with the codebase should confirm.

Remove " " from Album-Artist.

---

Assets/Script/Audio/AudioOptions.cs
Assets/Script/Gameplay/GameManager.Audio.cs
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Settings/Localization/Settings Shared Data.asset
Assets/Settings/Localization/Settings_en-US.asset

Changes the "Use Starpower FX" toggle to a drop down. "Off" and "Always" do what the toggle used to do. "Multitrack Only" reverbs only if you're using an instrument specific stem, will not reverb the song stem.

Starpower SFX only on multitrack songs.

---

Assets/Script/Integration/StageKit/StageKitGameplay.cs

Cues were being killed (stopped), but the LEDs were not actually being turned off. Would cause the LEDs to look like they were 'hanging unresponsive.' No LEDs are ever on when Strobe Fast is.

Fixed small Stage Kit oversight.

---

Assets/Art/Shaders/Gameplay/LitFade.shadergraph

Slightly tweaked the `Emission with color correction` setting to make the default kick and open note colors look less distorted. The kick color now much more closely resembles orange than yellow and better matches the RB4 kick color.
- Works well with most colors (such as purple, red, blue, etc) and does not distort them.
- For some cases like green, the color can be slightly off (green appears ever so slightly yellowish, for example), but this was an issue present before these changes.

Update LitFade shader kick color correction

---

Assets/Script/Gameplay/GameManager.Loading.cs
Assets/Script/Menu/History/ViewTypes/GameRecordViewType.cs
Assets/Script/Menu/History/ViewTypes/ReplayViewType.cs
Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
Assets/Script/Menu/MusicLibrary/RecommendedSongs.cs
Assets/Script/Menu/Persistent/MusicPlayer.cs
Assets/Script/Menu/Settings/SongManager/SettingsDirectory.cs
Assets/Script/Persistent/GlobalVariables.cs
Assets/Script/Persistent/LoadingManager.cs
Assets/Script/Scores/ScoreContainer.cs
Assets/Script/Song/SongContainer.cs
Assets/Script/Song/SongExport.cs
Assets/Script/Song/SongSearching.cs

The lifetime for access to all the variables contained in the class spans the entire uptime of the app. Having them all be statically accessible directly from the class itself instead of indirectly through a GlobalVariables instance makes operations on it easier to follow.
+ Extra benefit on fewer allocations through not having to create new lists.

Convert SongContainer to a static class

---

Assets/Script/Gameplay/Player/TrackPlayer.cs

Fixes a bug where the bass groove text pops up when you get the 6x multiplier under star power instead of 12x:

Take star power into account when checking for bass groove

---

Assets/Script/Menu/MusicLibrary/SongSearchingField.cs

- Replace Whole Word Regex with assigning to `filter:search_field_text` to search query

Fixed songs disappearing after pressing search filter with search input

---

Assets/Script/Integration/StageKit/StageKitInterpreter.cs

Adding this null check fixes the problem of having camera cuts which then use Next before a venue cue is set.

Handle camera cut before venue set

---

Assets/Prefabs/SettingPreviews/DMXInformationPanelUI.prefab
Assets/Script/Integration/MasterLightingController.cs
Assets/Script/Integration/MasterLightingGameplayMonitor.cs
Assets/Script/Integration/Sacn/SacnHardware.cs
Assets/Script/Integration/StageKit/StageKitHardware.cs
Assets/Script/Integration/StageKit/StageKitInterpreter.cs
Assets/Script/Integration/StageKit/StageKitLighting.Cues.cs
Assets/Script/Integration/StageKit/StageKitLighting.Primitives.cs

Dischord was enabling all of its primitives when it was enabled, since it swaps between the two blue patterns it shouldn't turn them both on at the same time at start, also some formatting changes.

Bug fix for Dischord and formatting

---

Assets/Plugins/Haukcode.sACN/README.txt
Assets/Script/Integration/Sacn/SacnHardware.cs
Assets/Settings/Localization/Settings_en-US.asset

There are instances when a strobe or fog call will happen the same frame as a light cue, in that case the cue change channel will miss one of them. This change means the fog and strobe state should be read directly from their respective existing state channels.

Removed Strobe and Fog from Cue Change channel

---

Assets/Script/Input/Bindings/BindingCollection.Templates.cs
Assets/Settings/Localization/Bindings Shared Data.asset
Assets/Settings/Localization/Bindings_en-US.asset

5-lane drums bindings previously reused the 4-lane localization strings, meaning the numbers were weird and Orange Cymbal was just blank. giving 5L its own strings means we can label orange and uniquely number all five lanes.

separate labels for 5-lane drum bindings

---

Assets/Script/Menu/Credits/CreditEntry.cs

Don't know if this is desired or not, but was playing around with it. It opens emails as a "mailto:" link.

Open email links.

---

Assets/Art/Fonts/Barlow/Barlow-Black.asset
Assets/Art/Fonts/Barlow/Barlow-Bold.asset
Assets/Art/Fonts/Barlow/Barlow-ExtraBold.asset
Assets/Art/Fonts/Barlow/Barlow-ExtraLight.asset
Assets/Art/Fonts/Barlow/Barlow-Light.asset
Assets/Art/Fonts/Barlow/Barlow-Medium.asset
Assets/Art/Fonts/Barlow/Barlow-Regular SDF.asset
Assets/Art/Fonts/Barlow/Barlow-SemiBold.asset
Assets/Art/Fonts/Barlow/Barlow-Thin.asset
Assets/Art/Fonts/RedHatDisplay/RedHatDisplay-Black.asset
Assets/Art/Fonts/RedHatDisplay/RedHatDisplay-Bold.asset
Assets/Art/Fonts/RedHatDisplay/RedHatDisplay-ExtraBold.asset
Assets/Art/Fonts/RedHatDisplay/RedHatDisplay-Light.asset
Assets/Art/Fonts/RedHatDisplay/RedHatDisplay-Medium.asset
Assets/Art/Fonts/RedHatDisplay/RedHatDisplay-SemiBold.asset
Assets/Art/Fonts/RedHatDisplay/RedHatDisplay.asset
Assets/Prefabs/Menu/MusicLibrary/PopupMenuItem.prefab

- proper fallback for all used fonts to NotoSans (only non-italic for now)
-> fixes text not displaying properly in popup menu
- new text overflow setting in music library popup menu, now truncates text with ellipsis (before text would go on multiple lines overlapping other entries)

Followup fixes to NotoSans Font addition

---

Assets/Prefabs/Menu/MusicLibrary/SongView.prefab
Assets/Script/Menu/MusicLibrary/SongView.cs
Assets/Script/Menu/MusicLibrary/ViewTypes/SortHeaderViewType.cs
Assets/Script/Menu/MusicLibrary/ViewTypes/ViewType.cs

for your long playlist name needs, fixes #753
- Added a new group in the SongView prefab with a second primary text as suggested by EliteAsian
- The swap happens depending on which background is chosen
Feedback is appreciated. Not quite familiar with the codebase layout yet.

Wider text field for playlist category header text

---

Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
Assets/Script/Menu/Navigation/NavigationScheme.cs
Assets/Script/Menu/Navigation/Navigator.cs

Hold orange + strum up and down to go to next/previous sections, seems like a capability that was in a previous version as discussed here: https://github.com/YARC-Official/YARG/issues/755
https://github.com/YARC-Official/YARG/assets/141366895/3a81e04a-73d9-4605-a4fb-eb02ac788916

Re-implement holding down the orange fret for section navigation in MusicLibrary

---

Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
Assets/Script/Menu/Navigation/NavigationScheme.cs
Assets/Script/Menu/Persistent/HelpBarButton.cs

After #756 since the menu opening was moved to on button release it doesn't trigger the opening the menu, adding in the onPointerUp on the HelperButton in the menu footer to trigger it.

Fix More Options menu not opening on click

---

Assets/Script/Input/Bindings/BindingCollection.Templates.cs
Assets/Script/Input/Bindings/ButtonBinding.cs
Assets/Script/Input/Bindings/ControlBinding.cs
Assets/Script/Input/Bindings/IndividualButtonBinding.cs
Assets/Script/Menu/ProfileInfo/EditBinds/BindGroups/BindHeader.cs
Assets/Settings/Localization/Bindings Shared Data.asset
Assets/Settings/Localization/Bindings_en-US.asset

Renumbered four-lane cymbals to match their lanes, expanded Green Cymbal string to encompass its role as Red Cymbal

update 4L Cymbal binding strings to account for Lefty Flip

---

Assets/Plugins/Haukcode.sACN/SACNClient.cs

Vestigial oversight from when this library also received. Shouldn't bind to a port when just sending. That would lock out/crash program who would try to bind to that same port.

Removed udp port binding

---

Assets/Script/Integration/Sacn/SacnInterpreter.cs
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/Settings/SettingsManager.cs
Assets/Settings/Localization/Settings Shared Data.asset
Assets/Settings/Localization/Settings_en-US.asset

An advanced setting, this allows the Master Dimmers to be set to something other than 255 on game start, as some fixture don't have 100% at 255 for some reason...

Added Master Dimmer values setting

---

Assets/Script/Menu/MusicLibrary/ViewTypes/SongViewType.cs
Assets/Script/Scores/ScoreContainer.cs
Assets/Script/Scores/ScoreDatabaseQueries.cs

Re-submission of pull #779
Now finds and displays the highest % score achieved for the same instrument+difficulty and displays that instead of the % score achieved on the highest scoring run.
Assumes the `Percent` column exists in the `PlayerScores` table exists (which it does on this `engine-refactor` branch).
The additional query should be performant enough, runs in 14ms on my db of 1021 rows whereas the original query runs in 4ms.

Show best % score for instrument and difficulty of the highest score

---

Assets/Script/Helpers/Extensions/InstrumentExtensions.cs
Assets/Script/Menu/MusicLibrary/DifficultyRing.cs
Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
Assets/Script/Menu/MusicLibrary/RecommendedSongs.cs
Assets/Script/Menu/MusicLibrary/Sidebar.cs
Assets/Script/Menu/MusicLibrary/SongSearchingField.cs
Assets/Script/Menu/MusicLibrary/ViewTypes/CategoryViewType.cs
Assets/Script/Menu/MusicLibrary/ViewTypes/SongViewType.cs
Assets/Script/Song/OptimizedFuzzySharp.cs
Assets/Script/Song/SongContainer.cs
Assets/Script/Song/SongSearching.cs

+ Establish `Fuzzy` as the default search - we now use `Contains` as a result value specifier in unspecified ranking (comes with fix to application of `Exact` search mode).
+ Do away with a lot of the IEnumerable usage - instead utilizing direct arrays.
+ Other SongSearch refactors

Additional Refactor Around Sorting & Searching

---

Assets/Script/Menu/MusicLibrary/PopupMenu.cs

The recent PR/commits that ignore articles when sorting had a bug in the Section Popup Menu for Artist/Album/Artist-Album sort. This would cause the sort to be "mis-sorted" in the menu since it was not ignoring the article. This PR resolves that.

Fix Sorting Error in Section Popup Menu

---

.gitignore
Assets/Editor/Build.meta
Assets/Editor/Build/BuildGitCommitVersion.cs
Assets/Editor/Build/BuildGitCommitVersion.cs.meta
Assets/Script/Menu/Main/MainMenu.cs
Assets/Script/Menu/Persistent/DevWatermark.cs
Assets/Script/Persistent/GlobalVariables.cs
Assets/Script/Scores/ScoreContainer.cs

Pulls information about the current git branch and commit to set the game version for display when in the Unity Editor and Development or Nightly builds.
`git rev-parse --abbrev-ref HEAD` - Gets the branch name at the HEAD.
`git rev-list --count HEAD` - Gets the number of commits at the HEAD.
`git rev-parse --short HEAD` - Gets the short hash of the current commit at HEAD.
During the build process, an Editor script runs and the version is saved to a `version.txt` file in the `Assets/Resources/` folder. If the game is development or nightly, it will pull the version from this file. If not, it uses the constant string in `GlobalVariables`, which should still be set for stable builds.
Needs some brief testing for Mac and Linux as it uses the `Process` class when running in Editor and during …

Use Git commit information for Game Version

---

Assets/Script/Gameplay/HUD/Practice/PracticeSectionMenu.cs
Assets/Script/Menu/Common/ListMenu/ListMenu.cs
Assets/Script/Menu/History/HistoryMenu.cs
Assets/Script/Menu/MusicLibrary/MusicLibraryMenu.cs
Assets/Script/Menu/Navigation/NavigationGroup.cs
Assets/Script/Menu/Navigation/NavigationScheme.cs
Assets/Script/Settings/SettingsManager.Settings.cs
Assets/Script/Settings/SettingsManager.cs
Assets/Settings/Localization/Settings Shared Data.asset
Assets/Settings/Localization/Settings_en-US.asset

Replaced clamp functions on nav selection index. More lines, but arguably better for UX. Addresses issue [YARG-178](https://yarg.youtrack.cloud/issue/YARG-178/Allow-wrap-around-when-navigating-lists-with-a-controller)

Wrap-around navigation for menus

---

Assets/StreamingAssets/lang/en-US.json

This was already being referenced by ScoreScreenMenu and was coming up blank.

Added a localization entry for Menu.Common.Continue
